/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual.entrega;

import data.cliente.Cliente;
import data.cliente.ClienteDao;
import data.entrega.Entrega;
import data.entrega.EntregaDao;
import data.pedido.Pedido;
import data.pedido.PedidoDao;
import data.pedidoTemProduto.PedidoTemProduto;
import data.pedidoTemProduto.PedidoTemProdutoDao;
import data.pedidoTemProduto.PedidoTemProdutoTableModel;
import data.produto.ProdutoDao;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Nelson
 */
public class TelaDelEntrega extends javax.swing.JFrame {

    /**
     * Creates new form TelaDelEntrega
     */
    
    private int codigoPedido;
    private int codigoEntrega;
    private double valorTotal=0;
    private String[] colunas = {"Codigo", "Produto", "Quantidade", "Valor"};
    private PedidoTemProdutoTableModel tableModel = new PedidoTemProdutoTableModel(colunas);
    
    
    public TelaDelEntrega() {
        initComponents();
        
        tablePedido.setModel(tableModel);
        btnExcluir.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextField27 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        txtConsulta = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        aaaa = new javax.swing.JScrollPane();
        tablePedido = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        txtCep = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        planodefundolabel = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel2.setText("Cod Entrega:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 70, 30);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(80, 10, 60, 30);

        jTextField2.setEditable(false);
        jTextField2.setEnabled(false);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(30, 80, 130, 30);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(30, 140, 50, 30);

        jLabel3.setText("Nome:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 60, 40, 20);

        jLabel6.setText("N:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 120, 20, 20);

        jLabel4.setText("Telefone:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(210, 60, 60, 20);

        jTextField3.setEditable(false);
        jTextField3.setEnabled(false);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(210, 80, 120, 30);

        jLabel7.setText("Bairro:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(210, 120, 40, 20);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(210, 140, 120, 30);

        jLabel8.setText("Cidade:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(390, 120, 50, 20);
        jPanel1.add(jTextField7);
        jTextField7.setBounds(390, 140, 160, 30);

        jLabel5.setText("Endereço:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(390, 60, 60, 20);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(390, 80, 160, 30);

        jButton1.setText("Procurar");
        jButton1.setToolTipText("procurar pedido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(150, 10, 90, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cod Produto", "Produto", "Quantidade", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Long.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 190, 550, 140);

        jButton2.setText("Alterar");
        jButton2.setToolTipText("Confirmar Entrega");
        jPanel1.add(jButton2);
        jButton2.setBounds(270, 390, 90, 40);

        jButton3.setText("Sair");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(380, 390, 100, 40);

        jLabel10.setText("Total a Pagar:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(90, 390, 100, 40);

        jTextField9.setEditable(false);
        jTextField9.setEnabled(false);
        jPanel1.add(jTextField9);
        jTextField9.setBounds(170, 390, 90, 40);

        jLabel11.setText("CEP:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(100, 120, 23, 20);
        jPanel1.add(jTextField10);
        jTextField10.setBounds(100, 140, 90, 30);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jLabel9.setText("Cod Entrega:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 10, 70, 30);
        jPanel2.add(jTextField8);
        jTextField8.setBounds(80, 10, 60, 30);

        jTextField11.setEditable(false);
        jTextField11.setEnabled(false);
        jPanel2.add(jTextField11);
        jTextField11.setBounds(30, 80, 130, 30);
        jPanel2.add(jTextField12);
        jTextField12.setBounds(30, 140, 50, 30);

        jLabel12.setText("Nome:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(30, 60, 40, 20);

        jLabel13.setText("N:");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(30, 120, 20, 20);

        jLabel14.setText("Telefone:");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(210, 60, 60, 20);

        jTextField13.setEditable(false);
        jTextField13.setEnabled(false);
        jPanel2.add(jTextField13);
        jTextField13.setBounds(210, 80, 120, 30);

        jLabel15.setText("Bairro:");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(210, 120, 40, 20);
        jPanel2.add(jTextField14);
        jTextField14.setBounds(210, 140, 120, 30);

        jLabel16.setText("Cidade:");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(390, 120, 50, 20);
        jPanel2.add(jTextField15);
        jTextField15.setBounds(390, 140, 160, 30);

        jLabel17.setText("Endereço:");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(390, 60, 60, 20);
        jPanel2.add(jTextField16);
        jTextField16.setBounds(390, 80, 160, 30);

        jButton4.setText("Procurar");
        jButton4.setToolTipText("procurar pedido");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(150, 10, 90, 30);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cod Produto", "Produto", "Quantidade", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Long.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(jTable2);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(20, 190, 550, 140);

        jButton5.setText("Alterar");
        jButton5.setToolTipText("Confirmar Entrega");
        jPanel2.add(jButton5);
        jButton5.setBounds(270, 390, 90, 40);

        jButton6.setText("Sair");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(380, 390, 100, 40);

        jLabel18.setText("Total a Pagar:");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(90, 390, 100, 40);

        jTextField17.setEditable(false);
        jTextField17.setEnabled(false);
        jPanel2.add(jTextField17);
        jTextField17.setBounds(170, 390, 90, 40);

        jLabel19.setText("CEP:");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(100, 120, 23, 20);
        jPanel2.add(jTextField18);
        jTextField18.setBounds(100, 140, 90, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 30, 590, 440);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(null);

        jLabel20.setText("Cod Entrega:");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(10, 10, 70, 30);
        jPanel3.add(jTextField19);
        jTextField19.setBounds(80, 10, 60, 30);

        jTextField20.setEditable(false);
        jTextField20.setEnabled(false);
        jPanel3.add(jTextField20);
        jTextField20.setBounds(30, 80, 130, 30);
        jPanel3.add(jTextField21);
        jTextField21.setBounds(30, 140, 50, 30);

        jLabel21.setText("Nome:");
        jPanel3.add(jLabel21);
        jLabel21.setBounds(30, 60, 40, 20);

        jLabel22.setText("N:");
        jPanel3.add(jLabel22);
        jLabel22.setBounds(30, 120, 20, 20);

        jLabel23.setText("Telefone:");
        jPanel3.add(jLabel23);
        jLabel23.setBounds(210, 60, 60, 20);

        jTextField22.setEditable(false);
        jTextField22.setEnabled(false);
        jPanel3.add(jTextField22);
        jTextField22.setBounds(210, 80, 120, 30);

        jLabel24.setText("Bairro:");
        jPanel3.add(jLabel24);
        jLabel24.setBounds(210, 120, 40, 20);
        jPanel3.add(jTextField23);
        jTextField23.setBounds(210, 140, 120, 30);

        jLabel25.setText("Cidade:");
        jPanel3.add(jLabel25);
        jLabel25.setBounds(390, 120, 50, 20);
        jPanel3.add(jTextField24);
        jTextField24.setBounds(390, 140, 160, 30);

        jLabel26.setText("Endereço:");
        jPanel3.add(jLabel26);
        jLabel26.setBounds(390, 60, 60, 20);
        jPanel3.add(jTextField25);
        jTextField25.setBounds(390, 80, 160, 30);

        jButton7.setText("Procurar");
        jButton7.setToolTipText("procurar pedido");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7);
        jButton7.setBounds(150, 10, 90, 30);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cod Produto", "Produto", "Quantidade", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Long.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(jTable3);

        jPanel3.add(jScrollPane3);
        jScrollPane3.setBounds(20, 190, 550, 140);

        jButton8.setText("Alterar");
        jButton8.setToolTipText("Confirmar Entrega");
        jPanel3.add(jButton8);
        jButton8.setBounds(270, 390, 90, 40);

        jButton9.setText("Sair");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton9);
        jButton9.setBounds(380, 390, 100, 40);

        jLabel27.setText("Total a Pagar:");
        jPanel3.add(jLabel27);
        jLabel27.setBounds(90, 390, 100, 40);

        jTextField26.setEditable(false);
        jTextField26.setEnabled(false);
        jPanel3.add(jTextField26);
        jTextField26.setBounds(170, 390, 90, 40);

        jLabel28.setText("CEP:");
        jPanel3.add(jLabel28);
        jLabel28.setBounds(100, 120, 23, 20);
        jPanel3.add(jTextField27);
        jTextField27.setBounds(100, 140, 90, 30);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cancelamento de Entrega - TradeTech 1.0");
        getContentPane().setLayout(null);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(null);

        jLabel29.setForeground(java.awt.Color.lightGray);
        jLabel29.setText("Cod Entrega:");
        jPanel4.add(jLabel29);
        jLabel29.setBounds(10, 10, 70, 30);

        txtConsulta.setBackground(new java.awt.Color(18, 18, 20));
        txtConsulta.setForeground(new java.awt.Color(204, 204, 204));
        txtConsulta.setBorder(null);
        jPanel4.add(txtConsulta);
        txtConsulta.setBounds(80, 10, 100, 30);

        txtNome.setEditable(false);
        txtNome.setBackground(new java.awt.Color(18, 18, 20));
        txtNome.setForeground(new java.awt.Color(204, 204, 204));
        txtNome.setBorder(null);
        txtNome.setEnabled(false);
        jPanel4.add(txtNome);
        txtNome.setBounds(20, 80, 130, 30);

        txtNumero.setEditable(false);
        txtNumero.setBackground(new java.awt.Color(18, 18, 20));
        txtNumero.setForeground(new java.awt.Color(204, 204, 204));
        txtNumero.setBorder(null);
        txtNumero.setEnabled(false);
        jPanel4.add(txtNumero);
        txtNumero.setBounds(20, 140, 50, 30);

        jLabel30.setForeground(java.awt.Color.lightGray);
        jLabel30.setText("Nome:");
        jPanel4.add(jLabel30);
        jLabel30.setBounds(20, 60, 40, 20);

        jLabel31.setForeground(java.awt.Color.lightGray);
        jLabel31.setText("N:");
        jPanel4.add(jLabel31);
        jLabel31.setBounds(20, 120, 20, 20);

        jLabel32.setForeground(java.awt.Color.lightGray);
        jLabel32.setText("Telefone:");
        jPanel4.add(jLabel32);
        jLabel32.setBounds(240, 60, 60, 20);

        txtTelefone.setEditable(false);
        txtTelefone.setBackground(new java.awt.Color(18, 18, 20));
        txtTelefone.setForeground(new java.awt.Color(204, 204, 204));
        txtTelefone.setBorder(null);
        txtTelefone.setEnabled(false);
        jPanel4.add(txtTelefone);
        txtTelefone.setBounds(240, 80, 120, 30);

        jLabel33.setForeground(java.awt.Color.lightGray);
        jLabel33.setText("Bairro:");
        jPanel4.add(jLabel33);
        jLabel33.setBounds(240, 120, 40, 20);

        txtBairro.setEditable(false);
        txtBairro.setBackground(new java.awt.Color(18, 18, 20));
        txtBairro.setForeground(new java.awt.Color(204, 204, 204));
        txtBairro.setBorder(null);
        txtBairro.setEnabled(false);
        jPanel4.add(txtBairro);
        txtBairro.setBounds(240, 140, 120, 30);

        jLabel34.setForeground(java.awt.Color.lightGray);
        jLabel34.setText("Cidade:");
        jPanel4.add(jLabel34);
        jLabel34.setBounds(410, 120, 50, 20);

        txtCidade.setEditable(false);
        txtCidade.setBackground(new java.awt.Color(18, 18, 20));
        txtCidade.setForeground(new java.awt.Color(204, 204, 204));
        txtCidade.setBorder(null);
        txtCidade.setEnabled(false);
        jPanel4.add(txtCidade);
        txtCidade.setBounds(410, 140, 160, 30);

        jLabel35.setForeground(java.awt.Color.lightGray);
        jLabel35.setText("Endereço:");
        jPanel4.add(jLabel35);
        jLabel35.setBounds(410, 60, 60, 20);

        txtEndereco.setEditable(false);
        txtEndereco.setBackground(new java.awt.Color(18, 18, 20));
        txtEndereco.setForeground(new java.awt.Color(204, 204, 204));
        txtEndereco.setBorder(null);
        txtEndereco.setEnabled(false);
        jPanel4.add(txtEndereco);
        txtEndereco.setBounds(410, 80, 160, 30);

        jButton10.setBackground(new java.awt.Color(3, 62, 11));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton10.setForeground(java.awt.SystemColor.control);
        jButton10.setText("Procurar");
        jButton10.setToolTipText("procurar pedido");
        jButton10.setBorderPainted(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton10);
        jButton10.setBounds(190, 10, 90, 30);

        tablePedido.setBackground(java.awt.Color.lightGray);
        tablePedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cod Produto", "Produto", "Quantidade", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Long.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePedido.setGridColor(new java.awt.Color(0, 0, 0));
        aaaa.setViewportView(tablePedido);

        jPanel4.add(aaaa);
        aaaa.setBounds(20, 190, 550, 150);

        btnExcluir.setBackground(new java.awt.Color(3, 62, 11));
        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnExcluir.setForeground(java.awt.SystemColor.control);
        btnExcluir.setText("Excluir");
        btnExcluir.setToolTipText("Confirmar Entrega");
        btnExcluir.setBorderPainted(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel4.add(btnExcluir);
        btnExcluir.setBounds(330, 380, 90, 40);

        jButton12.setBackground(new java.awt.Color(3, 62, 11));
        jButton12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton12.setForeground(java.awt.SystemColor.control);
        jButton12.setText("Sair");
        jButton12.setBorderPainted(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton12);
        jButton12.setBounds(440, 380, 90, 40);

        jLabel36.setForeground(java.awt.Color.lightGray);
        jLabel36.setText("Total a Pagar:");
        jPanel4.add(jLabel36);
        jLabel36.setBounds(20, 380, 80, 40);

        txtTotal.setEditable(false);
        txtTotal.setBackground(new java.awt.Color(18, 18, 20));
        txtTotal.setForeground(new java.awt.Color(204, 204, 204));
        txtTotal.setBorder(null);
        txtTotal.setEnabled(false);
        jPanel4.add(txtTotal);
        txtTotal.setBounds(100, 380, 90, 40);

        jLabel37.setForeground(java.awt.Color.lightGray);
        jLabel37.setText("CEP:");
        jPanel4.add(jLabel37);
        jLabel37.setBounds(100, 120, 30, 20);

        txtCep.setEditable(false);
        txtCep.setBackground(new java.awt.Color(18, 18, 20));
        txtCep.setForeground(new java.awt.Color(204, 204, 204));
        txtCep.setBorder(null);
        txtCep.setEnabled(false);
        jPanel4.add(txtCep);
        txtCep.setBounds(100, 140, 90, 30);

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundocliente1.png"))); // NOI18N
        jLabel38.setText("jLabel30");
        jPanel4.add(jLabel38);
        jLabel38.setBounds(0, 0, 590, 440);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(20, 70, 590, 440);

        jLabel1.setForeground(java.awt.Color.lightGray);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FotoJet (21).png"))); // NOI18N
        jLabel1.setText("Cancelamento e exclusão de entrega:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 10, 550, 90);

        planodefundolabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/planodefundoapp.png"))); // NOI18N
        planodefundolabel.setText("Fundo");
        getContentPane().add(planodefundolabel);
        planodefundolabel.setBounds(0, 0, 640, 530);

        setSize(new java.awt.Dimension(648, 565));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if (validaConsulta()) {
            EntregaDao entregaDao = new EntregaDao();
            String consulta = txtConsulta.getText();
            Entrega entrega = entregaDao.consulta(consulta);
            if (entrega != null) {
                codigoEntrega = entrega.getCodigo();
                codigoPedido = entrega.getCodigoPedido();
                PedidoTemProdutoDao pedidoTemProdutoDao = new PedidoTemProdutoDao();
                List<PedidoTemProduto> pedidoTemProdutos = pedidoTemProdutoDao.consultaPedido(codigoPedido);

                ProdutoDao produtoDao = new ProdutoDao();

                for (int i = 0; i < pedidoTemProdutos.size(); i++) {
                    String produto = produtoDao.consulta(String.valueOf(pedidoTemProdutos.get(i).getCodigoProduto())).getNome();
                    pedidoTemProdutos.get(i).setProduto(produto);
                }

                tableModel.limpaTabela();
                tableModel.adicionaVariasLinhas(pedidoTemProdutos);

                setTxtValorTotal(tableModel.getValorTotal());

                PedidoDao pedidoDao = new PedidoDao();
                
                ClienteDao clienteDao = new ClienteDao();
                Pedido pedido = pedidoDao.consulta(String.valueOf(codigoPedido));
                Cliente cliente = clienteDao.consultaCodigo(pedido.getCodigoCliente());

                txtNome.setText(cliente.getNome());
                txtTelefone.setText(pedido.getTelefone());
                txtEndereco.setText(pedido.getLogradouro());
                txtNumero.setText(String.valueOf(pedido.getNumero()));
                txtCep.setText(pedido.getTelefone());
                txtBairro.setText(pedido.getTelefone());
                txtCidade.setText(pedido.getTelefone());

                if(entrega.getStatus().equalsIgnoreCase("enviado")){
                    JOptionPane.showMessageDialog(null, "Entrega já enviada");
                }else{
                    btnExcluir.setEnabled(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Erro: Entrega não encontrado");
                txtConsulta.requestFocus();
            }
            entregaDao.desconectar();
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        EntregaDao entregaDao = new EntregaDao();
        PedidoDao pedidoDao = new PedidoDao();
        if(entregaDao.excluir(codigoPedido)){
            if(pedidoDao.updade(codigoPedido, "Entrega cancelada")==1){
                JOptionPane.showMessageDialog(null, "Excluida a entrega");
                btnExcluir.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private boolean validaConsulta() {
        if (txtConsulta.getText().length() > 0) {
            return true;
        }
        JOptionPane.showMessageDialog(null, "Erro: Codigo invalido");
        txtConsulta.requestFocus();
        return false;
    }
    
    private void setTxtValorTotal(double valor) {
        txtTotal.setText(String.valueOf(valor).replace(".", ","));
        valorTotal = valor;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDelEntrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDelEntrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDelEntrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDelEntrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDelEntrega().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane aaaa;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel planodefundolabel;
    private javax.swing.JTable tablePedido;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtConsulta;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
