/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual.consultas;

import data.produto.Produto;
import data.produto.ProdutoDao;
import data.produto.ProdutoTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Nelson
 */
public class TelaDelProd extends javax.swing.JFrame {

    /**
     * Creates new form TelaDelProd
     */
    
    ProdutoDao produtoDao = new ProdutoDao();
    ProdutoTableModel tableModel = new ProdutoTableModel();
    Produto produto = new Produto();
    
    public TelaDelProd() {
        initComponents();
        
        btnExcluir.setEnabled(false);
        tableProdutos.setModel(tableModel);
        atualizaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtConsulta = new javax.swing.JTextField();
        btnProcurar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        btnExcluir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProdutos = new javax.swing.JTable();
        jLabel31 = new javax.swing.JLabel();
        planodefundolabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Excluir Produto - TradeTech 1.0");
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FotoJet (18).png"))); // NOI18N
        jLabel1.setText("Excluir Produto:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 10, 330, 100);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel2.setForeground(java.awt.Color.lightGray);
        jLabel2.setText("Informe o Codigo do Produto:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 150, 30);

        txtConsulta.setBackground(new java.awt.Color(18, 18, 20));
        txtConsulta.setForeground(java.awt.Color.lightGray);
        txtConsulta.setBorder(null);
        jPanel1.add(txtConsulta);
        txtConsulta.setBounds(160, 10, 100, 30);

        btnProcurar.setBackground(new java.awt.Color(3, 62, 11));
        btnProcurar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnProcurar.setForeground(java.awt.SystemColor.control);
        btnProcurar.setText("Procurar");
        btnProcurar.setToolTipText("procurar produto para a exclusão");
        btnProcurar.setBorderPainted(false);
        btnProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarActionPerformed(evt);
            }
        });
        jPanel1.add(btnProcurar);
        btnProcurar.setBounds(270, 10, 90, 30);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(270, 150, 50, 20);

        jLabel4.setForeground(java.awt.Color.lightGray);
        jLabel4.setText("Produto:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 70, 60, 20);

        txtProduto.setEditable(false);
        txtProduto.setBackground(new java.awt.Color(18, 18, 20));
        txtProduto.setForeground(java.awt.Color.lightGray);
        txtProduto.setBorder(null);
        jPanel1.add(txtProduto);
        txtProduto.setBounds(10, 90, 110, 30);

        jLabel5.setForeground(java.awt.Color.lightGray);
        jLabel5.setText("Quantidade:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(190, 70, 70, 20);

        txtQuantidade.setEditable(false);
        txtQuantidade.setBackground(new java.awt.Color(18, 18, 20));
        txtQuantidade.setForeground(java.awt.Color.lightGray);
        txtQuantidade.setBorder(null);
        jPanel1.add(txtQuantidade);
        txtQuantidade.setBounds(190, 90, 90, 30);

        jLabel6.setForeground(java.awt.Color.lightGray);
        jLabel6.setText("Valor:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(350, 70, 60, 20);

        txtValor.setEditable(false);
        txtValor.setBackground(new java.awt.Color(18, 18, 20));
        txtValor.setForeground(java.awt.Color.lightGray);
        txtValor.setBorder(null);
        jPanel1.add(txtValor);
        txtValor.setBounds(350, 90, 80, 30);

        btnExcluir.setBackground(new java.awt.Color(3, 62, 11));
        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnExcluir.setForeground(java.awt.SystemColor.control);
        btnExcluir.setText("Excluir");
        btnExcluir.setToolTipText("Confirmar Exclusão");
        btnExcluir.setBorderPainted(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btnExcluir);
        btnExcluir.setBounds(200, 140, 80, 30);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 180, 510, 10);

        jLabel7.setText("Produto Excluido:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 190, 100, 20);

        jButton3.setBackground(new java.awt.Color(3, 62, 11));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setForeground(java.awt.SystemColor.control);
        jButton3.setText("Sair");
        jButton3.setToolTipText("Sair da Tela");
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(420, 353, 80, 40);

        tableProdutos.setBackground(java.awt.Color.lightGray);
        tableProdutos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cod Produto", "Produto", "Quantidade", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Long.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableProdutos);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 210, 480, 130);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundocliente1.png"))); // NOI18N
        jLabel31.setText("jLabel30");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(0, 0, 510, 400);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 70, 510, 400);

        planodefundolabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/planodefundoapp.png"))); // NOI18N
        planodefundolabel.setText("Fundo");
        getContentPane().add(planodefundolabel);
        planodefundolabel.setBounds(0, 0, 550, 490);

        setSize(new java.awt.Dimension(566, 522));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarActionPerformed
        if(validaConsulta()){
            produto = produtoDao.consulta(txtConsulta.getText());
            if(produto!=null){
                txtProduto.setText(produto.getNome());
                txtQuantidade.setText(String.valueOf(produto.getQuantidade()));
                txtValor.setText(String.valueOf(produto.getValor()));
                btnExcluir.setEnabled(true);
            }else{
                txtConsulta.requestFocus();
                JOptionPane.showMessageDialog(null, "Erro: Codigo invalido");
            }
        }
    }//GEN-LAST:event_btnProcurarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        
        if(produtoDao.excluir(produto.getCodigo())){
            JOptionPane.showMessageDialog(null, "Excluido com sucesso");
            btnExcluir.setEnabled(false);
            atualizaTabela();
        }else{
            JOptionPane.showMessageDialog(null, "Erro ao excluir");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private boolean validaConsulta(){
        if(txtConsulta.getText().length()>=1){
            return true;
        }
        txtConsulta.requestFocus();
        JOptionPane.showMessageDialog(null, "Erro: Codigo invalido");
        return false;
    }
    
    public void atualizaTabela(){
        tableModel.limpaTabela();
        tableModel.adicionaVariasLinhas(produtoDao.consultaTodos());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDelProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDelProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDelProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDelProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDelProd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnProcurar;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel planodefundolabel;
    private javax.swing.JTable tableProdutos;
    private javax.swing.JTextField txtConsulta;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
