/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual.consultas;

import data.funcionario.Funcionario;
import data.funcionario.FuncionarioDao;
import javax.swing.JOptionPane;

/**
 *
 * @author Nelson
 */
public class TelaRelFunc extends javax.swing.JFrame {

    FuncionarioDao funcionarioDao = new FuncionarioDao();
    
    /**
     * Creates new form TelaRelFunc
     */
    public TelaRelFunc() {
        initComponents();
        txtRa.setEditable(false);
        btnEditar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtRa = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDataNascimento = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txtLagradouro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCep = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cbxEstadoCivil = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cbxEstado = new javax.swing.JComboBox<>();
        btnEditar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCargo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtConsultaRa = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        txtSalario = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        planodefundolabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de Funcionários -TradeTech 1.0");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setToolTipText("Cadastro de Cliente");
        jPanel1.setLayout(null);

        txtRa.setBackground(new java.awt.Color(18, 18, 20));
        txtRa.setBorder(null);
        txtRa.setForeground(new java.awt.Color(204, 204, 204));
        try {
            txtRa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("############")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtRa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtRa);
        txtRa.setBounds(40, 70, 109, 30);

        jLabel4.setForeground(java.awt.Color.lightGray);
        jLabel4.setText("Nome:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(170, 70, 40, 30);

        txtNome.setBackground(new java.awt.Color(18, 18, 20));
        txtNome.setForeground(new java.awt.Color(204, 204, 204));
        txtNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNome.setBorder(null);
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jPanel1.add(txtNome);
        txtNome.setBounds(210, 70, 170, 30);

        jLabel5.setForeground(java.awt.Color.lightGray);
        jLabel5.setText("Nascimento:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(400, 70, 70, 30);

        txtDataNascimento.setBackground(new java.awt.Color(18, 18, 20));
        txtDataNascimento.setBorder(null);
        txtDataNascimento.setForeground(new java.awt.Color(204, 204, 204));
        try {
            txtDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataNascimento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDataNascimento.setToolTipText("Data de Nascimento");
        txtDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataNascimentoActionPerformed(evt);
            }
        });
        jPanel1.add(txtDataNascimento);
        txtDataNascimento.setBounds(470, 70, 120, 30);

        jLabel6.setForeground(java.awt.Color.lightGray);
        jLabel6.setText("Logradouro:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 160, 70, 30);

        txtLagradouro.setBackground(new java.awt.Color(18, 18, 20));
        txtLagradouro.setForeground(new java.awt.Color(204, 204, 204));
        txtLagradouro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLagradouro.setBorder(null);
        jPanel1.add(txtLagradouro);
        txtLagradouro.setBounds(80, 160, 110, 30);

        jLabel7.setForeground(java.awt.Color.lightGray);
        jLabel7.setText("Numero:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(220, 160, 50, 30);

        txtNumero.setBackground(new java.awt.Color(18, 18, 20));
        txtNumero.setForeground(new java.awt.Color(204, 204, 204));
        txtNumero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumero.setBorder(null);
        jPanel1.add(txtNumero);
        txtNumero.setBounds(270, 160, 70, 30);

        jLabel8.setForeground(java.awt.Color.lightGray);
        jLabel8.setText("CEP:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(370, 160, 30, 30);

        txtCep.setBackground(new java.awt.Color(18, 18, 20));
        txtCep.setBorder(null);
        txtCep.setForeground(new java.awt.Color(204, 204, 204));
        txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));
        txtCep.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtCep);
        txtCep.setBounds(400, 160, 70, 30);

        jLabel9.setForeground(java.awt.Color.lightGray);
        jLabel9.setText("Bairro:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(500, 160, 40, 30);

        txtBairro.setBackground(new java.awt.Color(18, 18, 20));
        txtBairro.setForeground(new java.awt.Color(204, 204, 204));
        txtBairro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBairro.setBorder(null);
        jPanel1.add(txtBairro);
        txtBairro.setBounds(540, 160, 100, 30);

        jLabel10.setForeground(java.awt.Color.lightGray);
        jLabel10.setText("Estado Civil:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(610, 70, 70, 30);

        cbxEstadoCivil.setBackground(new java.awt.Color(3, 62, 11));
        cbxEstadoCivil.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cbxEstadoCivil.setForeground(java.awt.SystemColor.control);
        cbxEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Solteiro(A)", "Casado(A)", "Divorciado(A)", "Viuvo(A)" }));
        cbxEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEstadoCivilActionPerformed(evt);
            }
        });
        jPanel1.add(cbxEstadoCivil);
        cbxEstadoCivil.setBounds(680, 70, 90, 30);

        jLabel11.setForeground(java.awt.Color.lightGray);
        jLabel11.setText("Cidade:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(32, 210, 50, 14);

        txtCidade.setBackground(new java.awt.Color(18, 18, 20));
        txtCidade.setForeground(new java.awt.Color(204, 204, 204));
        txtCidade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCidade.setBorder(null);
        jPanel1.add(txtCidade);
        txtCidade.setBounds(80, 200, 80, 30);

        jLabel12.setForeground(java.awt.Color.lightGray);
        jLabel12.setText("Estado:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(180, 200, 50, 30);

        cbxEstado.setBackground(new java.awt.Color(3, 62, 11));
        cbxEstado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cbxEstado.setForeground(java.awt.SystemColor.control);
        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jPanel1.add(cbxEstado);
        cbxEstado.setBounds(230, 200, 70, 30);

        btnEditar.setBackground(new java.awt.Color(3, 62, 11));
        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEditar.setForeground(java.awt.SystemColor.control);
        btnEditar.setText("Editar");
        btnEditar.setBorderPainted(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar);
        btnEditar.setBounds(660, 220, 100, 30);

        jLabel1.setForeground(java.awt.Color.lightGray);
        jLabel1.setText("RA:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(15, 70, 30, 30);

        jLabel2.setForeground(java.awt.Color.lightGray);
        jLabel2.setText("Salario:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(270, 110, 50, 30);

        jLabel3.setForeground(java.awt.Color.lightGray);
        jLabel3.setText("Cargo:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 110, 40, 30);

        txtCargo.setBackground(new java.awt.Color(18, 18, 20));
        txtCargo.setForeground(new java.awt.Color(204, 204, 204));
        txtCargo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCargo.setBorder(null);
        jPanel1.add(txtCargo);
        txtCargo.setBounds(50, 110, 150, 30);

        jLabel14.setForeground(java.awt.Color.lightGray);
        jLabel14.setText("Informe o RA do Funcionário:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(10, 25, 170, 20);

        txtConsultaRa.setBackground(new java.awt.Color(18, 18, 20));
        txtConsultaRa.setForeground(new java.awt.Color(204, 204, 204));
        txtConsultaRa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtConsultaRa.setBorder(null);
        jPanel1.add(txtConsultaRa);
        txtConsultaRa.setBounds(180, 20, 110, 30);

        btnConsultar.setBackground(new java.awt.Color(3, 62, 11));
        btnConsultar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnConsultar.setForeground(java.awt.SystemColor.control);
        btnConsultar.setText("Consultar");
        btnConsultar.setBorderPainted(false);
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultar);
        btnConsultar.setBounds(300, 20, 90, 30);

        txtSalario.setBackground(new java.awt.Color(18, 18, 20));
        txtSalario.setForeground(java.awt.Color.lightGray);
        txtSalario.setBorder(null);
        jPanel1.add(txtSalario);
        txtSalario.setBounds(330, 110, 100, 30);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundocliente1.png"))); // NOI18N
        jLabel31.setText("jLabel30");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(0, 0, 790, 270);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 60, 790, 270);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(java.awt.Color.lightGray);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FotoJet.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(230, 20, 300, 50);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FotoJet (1).png"))); // NOI18N
        jLabel18.setText("jLabel18");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(461, 10, 210, 70);

        planodefundolabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/planodefundoapp.png"))); // NOI18N
        planodefundolabel.setText("Fundo");
        getContentPane().add(planodefundolabel);
        planodefundolabel.setBounds(0, 0, 880, 370);

        setSize(new java.awt.Dimension(888, 404));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataNascimentoActionPerformed

    private void cbxEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEstadoCivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEstadoCivilActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if(validaCampos()){
            Funcionario funcionario = new Funcionario();
            
            funcionario.setRa(txtRa.getText());
            funcionario.setNome(txtNome.getText());
            funcionario.setCargo(txtCargo.getText());
            funcionario.setSalario(1000.00);
            funcionario.setDataNacimento(txtDataNascimento.getText());
            funcionario.setLagradouro(txtLagradouro.getText());
            funcionario.setNumero(Integer.parseInt(txtNumero.getText()));
            funcionario.setBairro(txtBairro.getText());
            funcionario.setCep(txtCep.getText());
            funcionario.setEstado(cbxEstado.getSelectedItem().toString());
            funcionario.setCidade(txtCidade.getText());
            funcionario.setEstadoCivil(cbxEstadoCivil.getSelectedItem().toString());
            
            switch (funcionarioDao.updade(funcionario)) {
                case 1: {
                    JOptionPane.showMessageDialog(null, "Salvo com sucesso");
                    dispose();
                    break;
                }
                default: {
                    JOptionPane.showMessageDialog(null, "Erro ao alterar");
                    break;
                }
            }
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        Funcionario funcionario;
        
        if (validaConsultar()) {
            funcionario = funcionarioDao.consulta(txtConsultaRa.getText());
            if(funcionario!=null){
                txtRa.setText(funcionario.getRa());
                txtSalario.setText(String.valueOf(funcionario.getSalario()));
                txtCargo.setText(funcionario.getCargo());
                txtNome.setText(funcionario.getNome());
                txtDataNascimento.setText(funcionario.getDataNacimento());
                cbxEstadoCivil.setSelectedItem(funcionario.getEstadoCivil());
                txtLagradouro.setText(funcionario.getLagradouro());
                txtNumero.setText(String.valueOf(funcionario.getNumero()));
                txtCep.setText(funcionario.getCep());
                txtBairro.setText(funcionario.getBairro());
                txtCidade.setText(funcionario.getCidade());
                cbxEstado.setSelectedItem(funcionario.getEstado());
                btnEditar.setEnabled(true);
            }else{
                JOptionPane.showMessageDialog(null, "Erro: Funcionario não encontrado");
                btnEditar.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private boolean validaConsultar(){
        boolean status = true;
        if (txtConsultaRa.getText().length()<1) {
            JOptionPane.showMessageDialog(null, "Erro: RA invalido");
            txtConsultaRa.requestFocus();
            status = false;
        }
        return status;
    }
    
    private boolean validaCampos() {
        boolean status = true;
        
        if (txtNome.getText().length()<2) {
            JOptionPane.showMessageDialog(null, "Erro: Nome invalido");
            txtNome.requestFocus();
            status = false;
        }
        else if (txtDataNascimento.getText().equals("  /  /    ")) {
            JOptionPane.showMessageDialog(null, "Erro: Nascimento invalido");
            txtDataNascimento.requestFocus();
            status = false;
        }
        else if (cbxEstadoCivil.getSelectedItem().toString().length()==1) {
            JOptionPane.showMessageDialog(null, "Erro: Selecione um estado civil");
            cbxEstadoCivil.requestFocus();
            return false;
        }
        else if (txtCargo.getText().length()<2) {
            JOptionPane.showMessageDialog(null, "Erro: Cargo invalido");
            txtCargo.requestFocus();
            status = false;
        }
        else if (txtSalario.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Erro: Salario invalido");
            txtSalario.requestFocus();
            status = false;
        }
        else if (txtLagradouro.getText().length()<2) {
            JOptionPane.showMessageDialog(null, "Erro: Logradouro invalido");
            txtLagradouro.requestFocus();
            status = false;
        }
        else if (txtCep.getText().equals("     -   ")) {
            JOptionPane.showMessageDialog(null, "Erro: Cep invalido");
            txtCep.requestFocus();
            status = false;
        }
        else if (txtBairro.getText().length()<2) {
            JOptionPane.showMessageDialog(null, "Erro: Bairro invalido");
            txtBairro.requestFocus();
            status = false;
        }
        else if (txtCidade.getText().length()<2) {
            JOptionPane.showMessageDialog(null, "Erro: Cidade invalido");
            txtCidade.requestFocus();
            status = false;
        }else if (cbxEstado.getSelectedItem().toString().length()==1) {
            JOptionPane.showMessageDialog(null, "Erro: Selecione um estado");
            cbxEstado.requestFocus();
            return false;
        }else{
            int numero;
            try {
                numero = Integer.parseInt(txtNumero.getText());
            } catch (NumberFormatException e) {
                numero=0;
            }
            if (numero<=0||numero>20000) {
                JOptionPane.showMessageDialog(null, "Erro: Numero invalido");
                txtNumero.requestFocus();
                return false;
            }
        }

        return status;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRelFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRelFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRelFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRelFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRelFunc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JComboBox<String> cbxEstadoCivil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel planodefundolabel;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtConsultaRa;
    private javax.swing.JFormattedTextField txtDataNascimento;
    private javax.swing.JTextField txtLagradouro;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JFormattedTextField txtRa;
    private javax.swing.JTextField txtSalario;
    // End of variables declaration//GEN-END:variables
}
