/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual.login;

import data.login.Login;
import data.login.LoginDao;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import visual.telaprincipal.TelaPrincipal;

/**
 *
 * @author Nelson
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    
    private LoginDao loginDao = new LoginDao();
    
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelLoggin = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jButtonEsqueci = new javax.swing.JButton();
        jButtonCadastro = new javax.swing.JButton();
        txtSenha = new javax.swing.JPasswordField();
        fundologgin = new javax.swing.JLabel();
        planodefundolabel = new javax.swing.JLabel();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loggin - TradeTech 1.0");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logoT.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(480, 488, 82, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("TradeTech - Soluções Tecnologicas Voltadas ao Pequeno Comercio.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 470, 380, 70);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jLabelLoggin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-usuário-24 (2).png"))); // NOI18N
        jLabelLoggin.setLabelFor(txtEmail);
        jPanel1.add(jLabelLoggin);
        jLabelLoggin.setBounds(70, 200, 60, 50);

        jLabelSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-privacidade-24.png"))); // NOI18N
        jPanel1.add(jLabelSenha);
        jLabelSenha.setBounds(70, 240, 60, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logooo.png"))); // NOI18N
        jLabel4.setText("Insira o Logo aqui");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(100, 50, 160, 135);

        txtEmail.setBackground(new java.awt.Color(18, 18, 20));
        txtEmail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(204, 204, 204));
        txtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmail.setToolTipText("Digite seu usuario para acessar o sistema");
        txtEmail.setBorder(null);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
        });
        jPanel1.add(txtEmail);
        txtEmail.setBounds(100, 210, 160, 30);
        txtEmail.getAccessibleContext().setAccessibleName("Email");

        btnLogin.setBackground(new java.awt.Color(3, 62, 11));
        btnLogin.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        btnLogin.setForeground(java.awt.SystemColor.control);
        btnLogin.setText("Login");
        btnLogin.setToolTipText("Botão para acessar o sistema");
        btnLogin.setBorder(null);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnLogin.setNextFocusableComponent(jButtonSair);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin);
        btnLogin.setBounds(90, 310, 80, 40);

        jButtonSair.setBackground(new java.awt.Color(3, 62, 11));
        jButtonSair.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        jButtonSair.setForeground(java.awt.SystemColor.control);
        jButtonSair.setText("Sair");
        jButtonSair.setToolTipText("Sair do sistema");
        jButtonSair.setBorder(null);
        jButtonSair.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonSair.setNextFocusableComponent(jButtonEsqueci);
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSair);
        jButtonSair.setBounds(180, 310, 80, 40);

        jButtonEsqueci.setBackground(new java.awt.Color(3, 62, 11));
        jButtonEsqueci.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButtonEsqueci.setForeground(java.awt.SystemColor.control);
        jButtonEsqueci.setToolTipText("Recadastrar Senha");
        jButtonEsqueci.setBorder(null);
        jButtonEsqueci.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonEsqueci.setLabel("Esqueci minha senha");
        jButtonEsqueci.setNextFocusableComponent(jButtonCadastro);
        jButtonEsqueci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEsqueciActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEsqueci);
        jButtonEsqueci.setBounds(90, 370, 170, 30);

        jButtonCadastro.setBackground(new java.awt.Color(3, 62, 11));
        jButtonCadastro.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        jButtonCadastro.setForeground(java.awt.SystemColor.control);
        jButtonCadastro.setToolTipText("Novo cadastro");
        jButtonCadastro.setBorder(null);
        jButtonCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonCadastro.setLabel("Cadastrar");
        jButtonCadastro.setNextFocusableComponent(jLabelLoggin);
        jButtonCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCadastro);
        jButtonCadastro.setBounds(90, 401, 170, 40);

        txtSenha.setBackground(new java.awt.Color(18, 18, 20));
        txtSenha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtSenha.setForeground(new java.awt.Color(204, 204, 204));
        txtSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSenha.setBorder(null);
        txtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaKeyPressed(evt);
            }
        });
        jPanel1.add(txtSenha);
        txtSenha.setBounds(100, 250, 160, 30);

        fundologgin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundologgin 4.png"))); // NOI18N
        fundologgin.setText("jLabel2");
        jPanel1.add(fundologgin);
        fundologgin.setBounds(10, 30, 360, 440);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(160, 0, 360, 470);

        planodefundolabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/planodefundoapp.png"))); // NOI18N
        planodefundolabel.setText("Fundo");
        getContentPane().add(planodefundolabel);
        planodefundolabel.setBounds(0, 0, 700, 590);

        setSize(new java.awt.Dimension(707, 605));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroActionPerformed
        
        TelaCadLogin telaCadLogin = new TelaCadLogin();
        telaCadLogin.setVisible(true);
//        JOptionPane.showMessageDialog(null,"Função Indisponivel no momento, procure seu Superior!");
    }//GEN-LAST:event_jButtonCadastroActionPerformed

    private void jButtonEsqueciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEsqueciActionPerformed
        String email = JOptionPane.showInputDialog("Digite o Seu Email do Cadastro:");
        String cpf = JOptionPane.showInputDialog("Infome o Seu CPF");

            JOptionPane.showMessageDialog(null,"Enviado Link para o novo Cadastro de Senha do CPF:"+cpf+" no Email: \n"+email);
    }//GEN-LAST:event_jButtonEsqueciActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        System.exit(0);// Sair do Sistema
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        Login login;
        
        if(validaCampos()){
            login = loginDao.consulta(txtEmail.getText());
            if (login != null) { // Validação
                if (login.getSenha().equals(txtSenha.getText())) {
                    TelaPrincipal tela = new TelaPrincipal(login.getRa()); //Chama JFrame Tela Principal e armazena na variavel tela
                    tela.setVisible(true); // Disponibiliza a Visibilidade da Classe JFrame
                    dispose(); // Fecha a tela atual
                } else {
                    JOptionPane.showMessageDialog(null, "Usuario ou Senha Invalidos!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Usuario ou Senha Invalidos!");
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private boolean validaCampos(){
        boolean status=false;
        
        if(validaCampoEmail()){
            if(validaCampoSenha()){
                status=true;
            }
        }
        
        return status;
    }
    
    private boolean validaCampoEmail(){
        boolean status=false;
        
        if(txtEmail.getText().length()>0){
            status=true;
        }else{
            JOptionPane.showMessageDialog(null, "Insira seu usuario");
            txtEmail.requestFocus();
        }
        return status;
    }
    
    private boolean validaCampoSenha(){
        boolean status=false;
        
        if(txtSenha.getText().length()>0){
            status=true;
        }else{
            JOptionPane.showMessageDialog(null, "Insira sua senha");
            txtSenha.requestFocus();
        }
        return status;
    }
    
    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        if(evt.getKeyCode()==10){
            if(validaCampoEmail()){
                txtSenha.requestFocus();
            }
        }
    }//GEN-LAST:event_txtEmailKeyPressed

    private void txtSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyPressed
        int tecla = evt.getKeyCode();
        if(tecla==10){
            if(validaCampoSenha()){
                java.awt.event.ActionEvent a = new ActionEvent(tecla, 0, ""); // evento falso
                btnLoginActionPerformed(a);
            }
        }
    }//GEN-LAST:event_txtSenhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            UIManager.put("Button.defaultButtonFollowsFocus", Boolean.TRUE); // Define o Entrer como Entrada no Botão em Foco 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel fundologgin;
    private javax.swing.JButton jButtonCadastro;
    private javax.swing.JButton jButtonEsqueci;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelLoggin;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel planodefundolabel;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
