/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual.login;

import data.funcionario.Funcionario;
import data.funcionario.FuncionarioDao;
import data.login.Login;
import data.login.LoginDao;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Pedro
 */
public class TelaCadLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadLogin
     */
    public TelaCadLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtRa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        txtConfirmaSenha = new javax.swing.JPasswordField();
        btnCadastrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        planodefundolabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(java.awt.Color.lightGray);
        jLabel1.setText("RA do funcionario");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 120, 100, 20);

        txtRa.setBackground(new java.awt.Color(18, 18, 20));
        txtRa.setForeground(new java.awt.Color(204, 204, 204));
        txtRa.setBorder(null);
        txtRa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRaActionPerformed(evt);
            }
        });
        getContentPane().add(txtRa);
        txtRa.setBounds(259, 120, 124, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(java.awt.Color.lightGray);
        jLabel2.setText("Digite um nome de usuario");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 160, 170, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(java.awt.Color.lightGray);
        jLabel3.setText("Senha");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 200, 40, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(java.awt.Color.lightGray);
        jLabel4.setText("Confirma a senha");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 240, 100, 20);

        txtUsuario.setBackground(new java.awt.Color(18, 18, 20));
        txtUsuario.setForeground(new java.awt.Color(204, 204, 204));
        txtUsuario.setBorder(null);
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(302, 160, 80, 14);

        txtSenha.setBackground(new java.awt.Color(18, 18, 20));
        txtSenha.setForeground(new java.awt.Color(204, 204, 204));
        txtSenha.setBorder(null);
        getContentPane().add(txtSenha);
        txtSenha.setBounds(302, 200, 80, 14);

        txtConfirmaSenha.setBackground(new java.awt.Color(18, 18, 20));
        txtConfirmaSenha.setForeground(new java.awt.Color(204, 204, 204));
        txtConfirmaSenha.setBorder(null);
        getContentPane().add(txtConfirmaSenha);
        txtConfirmaSenha.setBounds(302, 240, 80, 14);

        btnCadastrar.setBackground(new java.awt.Color(3, 62, 11));
        btnCadastrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCadastrar.setForeground(java.awt.SystemColor.control);
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setBorderPainted(false);
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        btnCadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCadastrarKeyPressed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(110, 300, 130, 30);

        btnCancelar.setBackground(new java.awt.Color(3, 62, 11));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancelar.setForeground(java.awt.SystemColor.control);
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorderPainted(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(250, 300, 130, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Para cadastrar é necessario ja ter cadastro de funcionario");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 40, 370, 15);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundocliente1.png"))); // NOI18N
        jLabel31.setText("jLabel30");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(30, 20, 440, 340);

        planodefundolabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/planodefundoapp.png"))); // NOI18N
        planodefundolabel.setText("Fundo");
        getContentPane().add(planodefundolabel);
        planodefundolabel.setBounds(0, 0, 520, 390);

        setSize(new java.awt.Dimension(516, 420));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if(validaCampos()){
            if(txtSenha.getText().equals(txtConfirmaSenha.getText())){
                Login login = new Login();
                LoginDao loginDao = new LoginDao();

                login.setUsuario(txtUsuario.getText());
                login.setSenha(txtSenha.getText());
                login.setRa(txtRa.getText());

                switch(loginDao.salvar(login)){
                    case 1:{
                        JOptionPane.showMessageDialog(null,"Usuario cadastrado");
                        dispose();
                        break;
                    }
                    default:{
                        JOptionPane.showMessageDialog(null,"Erro ao Cadastrar");
                        break;
                    }
                }
            }
        }else{
            JOptionPane.showMessageDialog(null,"Erro: algum campo errado");
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnCadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCadastrarKeyPressed
        int tecla = evt.getKeyCode();
        if(tecla==10){
            java.awt.event.ActionEvent a = new ActionEvent(tecla, 0, ""); // evento falso
            btnCadastrarActionPerformed(a);
        }
    }//GEN-LAST:event_btnCadastrarKeyPressed

    private void txtRaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRaActionPerformed

    private boolean validaCampos(){
        boolean status=true;
        
        if(txtRa.getText().length()<1){
            JOptionPane.showMessageDialog(null,"Erro: RA invalido");
            txtRa.requestFocus();
            status= false;
        }
        else if(txtUsuario.getText().length()<1){
            JOptionPane.showMessageDialog(null,"Erro: Usuario invalido");
            txtUsuario.requestFocus();
            status= false;
        }
        else if(txtSenha.getText().length()<1){
            JOptionPane.showMessageDialog(null,"Erro: Sanha invalida");
            txtSenha.requestFocus();
            status= false;
        }
        else if(txtConfirmaSenha.getText().length()<1){
            JOptionPane.showMessageDialog(null,"Erro: Confirmação de senha invalida");
            txtConfirmaSenha.requestFocus();
            status= false;
        }
        return status;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel planodefundolabel;
    private javax.swing.JPasswordField txtConfirmaSenha;
    private javax.swing.JTextField txtRa;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
