/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual.pedidos;

import data.cliente.Cliente;
import data.cliente.ClienteDao;
import data.pedido.Pedido;
import data.pedido.PedidoDao;
import data.pedidoTemProduto.PedidoTemProdutoTableModel;
import data.pedidoTemProduto.PedidoTemProduto;
import data.pedidoTemProduto.PedidoTemProdutoDao;
import data.produto.Produto;
import data.produto.ProdutoDao;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Nelson
 */
public class TelaDelPed extends javax.swing.JFrame {

    /**
     * Creates new form TelaDelPed
     */
    
    
    private String[] colunas = {"Codigo", "Produto", "Quantidade", "Valor"};
    private PedidoTemProdutoTableModel tableModel = new PedidoTemProdutoTableModel(colunas);
    private Pedido pedido;
    private double valorTotal=0;
    private int codigoPedido;
    
    public TelaDelPed() {
        initComponents();
        
        tablePedido.setModel(tableModel);
        setTxtValorTotal(valorTotal);
        btnExcluir.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtPedido = new javax.swing.JTextField();
        btnProcurar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePedido = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCep = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        planodefundolabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Excluir Pedido - TradeTech 1.0");
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Cod Pedido:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 70, 30);

        txtPedido.setBackground(new java.awt.Color(18, 18, 20));
        txtPedido.setForeground(new java.awt.Color(204, 204, 204));
        txtPedido.setBorder(null);
        jPanel1.add(txtPedido);
        txtPedido.setBounds(80, 10, 90, 30);

        btnProcurar.setBackground(new java.awt.Color(3, 62, 11));
        btnProcurar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnProcurar.setForeground(java.awt.SystemColor.control);
        btnProcurar.setText("Procurar");
        btnProcurar.setToolTipText("procurar pedido");
        btnProcurar.setBorderPainted(false);
        btnProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarActionPerformed(evt);
            }
        });
        jPanel1.add(btnProcurar);
        btnProcurar.setBounds(180, 10, 90, 30);

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Nome:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 60, 40, 20);

        txtNome.setEditable(false);
        txtNome.setBackground(new java.awt.Color(18, 18, 20));
        txtNome.setForeground(new java.awt.Color(204, 204, 204));
        txtNome.setBorder(null);
        txtNome.setEnabled(false);
        jPanel1.add(txtNome);
        txtNome.setBounds(10, 80, 130, 30);

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Telefone:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(180, 60, 60, 20);

        txtTelefone.setEditable(false);
        txtTelefone.setBackground(new java.awt.Color(18, 18, 20));
        txtTelefone.setForeground(new java.awt.Color(204, 204, 204));
        txtTelefone.setBorder(null);
        txtTelefone.setEnabled(false);
        jPanel1.add(txtTelefone);
        txtTelefone.setBounds(180, 80, 120, 30);

        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Endereço:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(350, 60, 60, 20);

        txtEndereco.setEditable(false);
        txtEndereco.setBackground(new java.awt.Color(18, 18, 20));
        txtEndereco.setForeground(new java.awt.Color(204, 204, 204));
        txtEndereco.setBorder(null);
        txtEndereco.setEnabled(false);
        jPanel1.add(txtEndereco);
        txtEndereco.setBounds(350, 80, 160, 30);

        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("N:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 120, 20, 20);

        txtNumero.setEditable(false);
        txtNumero.setBackground(new java.awt.Color(18, 18, 20));
        txtNumero.setForeground(new java.awt.Color(204, 204, 204));
        txtNumero.setBorder(null);
        txtNumero.setEnabled(false);
        jPanel1.add(txtNumero);
        txtNumero.setBounds(10, 140, 50, 30);

        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Bairro:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(250, 120, 40, 20);

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(18, 18, 20));
        jTextField6.setForeground(new java.awt.Color(204, 204, 204));
        jTextField6.setBorder(null);
        jTextField6.setEnabled(false);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(250, 140, 120, 30);

        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Cidade:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(420, 120, 50, 20);

        txtCidade.setEditable(false);
        txtCidade.setBackground(new java.awt.Color(18, 18, 20));
        txtCidade.setForeground(new java.awt.Color(204, 204, 204));
        txtCidade.setBorder(null);
        txtCidade.setEnabled(false);
        jPanel1.add(txtCidade);
        txtCidade.setBounds(420, 140, 160, 30);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 182, 600, 10);

        tablePedido.setBackground(new java.awt.Color(204, 204, 204));
        tablePedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cod Produto", "Produto", "Quantidade", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Long.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePedido.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tablePedido);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 230, 510, 140);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Itens do Pedido");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(230, 200, 130, 20);

        jButton2.setBackground(new java.awt.Color(3, 62, 11));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(java.awt.SystemColor.control);
        jButton2.setText("Sair");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(450, 400, 100, 30);

        btnExcluir.setBackground(new java.awt.Color(3, 62, 11));
        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnExcluir.setForeground(java.awt.SystemColor.control);
        btnExcluir.setText("Excluir");
        btnExcluir.setBorderPainted(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btnExcluir);
        btnExcluir.setBounds(330, 400, 100, 30);

        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Total a Pagar:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(40, 400, 70, 30);

        txtTotal.setEditable(false);
        txtTotal.setBackground(new java.awt.Color(18, 18, 20));
        txtTotal.setForeground(new java.awt.Color(204, 204, 204));
        txtTotal.setBorder(null);
        jPanel1.add(txtTotal);
        txtTotal.setBounds(120, 400, 80, 30);

        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("CEP:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(100, 120, 30, 20);

        txtCep.setEditable(false);
        txtCep.setBackground(new java.awt.Color(18, 18, 20));
        txtCep.setForeground(new java.awt.Color(204, 204, 204));
        txtCep.setBorder(null);
        txtCep.setEnabled(false);
        jPanel1.add(txtCep);
        txtCep.setBounds(100, 140, 110, 30);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundocliente1.png"))); // NOI18N
        jLabel31.setText("jLabel30");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(0, 0, 600, 450);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 60, 600, 450);

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FotoJet (28).png"))); // NOI18N
        jLabel1.setText("Excluir Pedido:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 400, 80);

        planodefundolabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/planodefundoapp.png"))); // NOI18N
        planodefundolabel.setText("Fundo");
        getContentPane().add(planodefundolabel);
        planodefundolabel.setBounds(0, 0, 640, 540);

        setSize(new java.awt.Dimension(654, 571));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarActionPerformed
        if(validaConsulta()){
            PedidoDao pedidoDao = new PedidoDao();
            ClienteDao clienteDao = new ClienteDao();
            PedidoTemProdutoDao pedidoTemProdutoDao = new PedidoTemProdutoDao();
            ProdutoDao produtoDao = new ProdutoDao();
            
            pedido = pedidoDao.consulta(txtPedido.getText());
            if(pedido!=null){
                Cliente cliente = clienteDao.consultaCodigo(pedido.getCodigoCliente());
                txtNome.setText(cliente.getNome());
                
                List<PedidoTemProduto> listaItensPedido = pedidoTemProdutoDao.consultaPedido(pedido.getCodigo());
                txtTelefone.setText(pedido.getTelefone());
                txtEndereco.setText(pedido.getBairro());
                txtCep.setText(pedido.getCep());
                txtCidade.setText(pedido.getCidade());
                txtEndereco.setText(pedido.getLogradouro());
                txtNumero.setText(String.valueOf(pedido.getNumero()));
                setTxtValorTotal(pedido.getValor());
                
                for (int i = 0; i < listaItensPedido.size(); i++) {
                    String codigoProduto = String.valueOf(listaItensPedido.get(i).getCodigoProduto());
                    Produto produto = produtoDao.consulta(codigoProduto);
                    
                    listaItensPedido.get(i).setProduto(produto.getNome());
                    listaItensPedido.get(i).setQuantidadeEstoque(produto.getQuantidade());
                }
                
                tableModel.limpaTabela();
                tableModel.adicionaVariasLinhas(listaItensPedido);
                setTxtValorTotal(tableModel.getValorTotal());
                codigoPedido = pedido.getCodigo();
                btnExcluir.setEnabled(true);
            }else{
                JOptionPane.showMessageDialog(null, "Erro: Pedido não encontrado");
            }
        }
    }//GEN-LAST:event_btnProcurarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        PedidoDao pedidoDao = new PedidoDao();
        PedidoTemProdutoDao pedidoTemProdutoDao = new PedidoTemProdutoDao();
        
        alterarEstoque(tableModel.getDados());
        
        pedidoDao.excluir(codigoPedido);
        pedidoTemProdutoDao.excluir(codigoPedido);
        JOptionPane.showMessageDialog(null, "Pedido excluido");
        btnExcluir.setEnabled(false);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void alterarEstoque(List<PedidoTemProduto> produtosDoPedido){
        produtosDoPedido.forEach(produtoDoPedido -> {
            ProdutoDao estoque = new ProdutoDao();
            estoque.updadeEstoque(produtoDoPedido.getCodigoProduto(), produtoDoPedido.getQuantidadeEstoque()+produtoDoPedido.getQuantidade());
        });
    }
    
    public void setValorTotal(double valorTotal) {
        this.valorTotal = valorTotal;
        setTxtValorTotal(valorTotal);
    }
    
    private void setTxtValorTotal(double valor){
        txtTotal.setText(String.valueOf(valor));
//        txtTotal.setText(String.valueOf(valor).replace(".", ","));
    }
    
    private boolean validaConsulta() {
        if (txtPedido.getText().length()>=1) {
            return true;
        }
        JOptionPane.showMessageDialog(null, "Erro: Pedido invalido");
        txtPedido.requestFocus();
        return false;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDelPed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDelPed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDelPed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDelPed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDelPed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnProcurar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel planodefundolabel;
    private javax.swing.JTable tablePedido;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPedido;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
