/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual.pedidos;

import data.cliente.Cliente;
import data.cliente.ClienteDao;
import data.pedido.Pedido;
import data.pedido.PedidoDao;
import data.pedidoTemProduto.PedidoTemProdutoTableModel;
import data.pedidoTemProduto.PedidoTemProduto;
import data.pedidoTemProduto.PedidoTemProdutoDao;
import data.produto.Produto;
import data.produto.ProdutoDao;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Nelson
 */
public class TelaAltPed extends javax.swing.JFrame {

    /**
     * Creates new form TelaAltPed
     */
    
    private PedidoTemProdutoTableModel tableModel = new PedidoTemProdutoTableModel();
    private List<PedidoTemProduto> listaProdutosPedidoNaoAlterado;
    private double valorTotal = 0;
    private int codigoPedido;
    private Pedido pedidoAlterado;
    
    public TelaAltPed() {
        initComponents();
        
        tablePedido.setModel(tableModel);
        setTxtValorTotal(valorTotal);
        btnConfirmar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtPedido = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePedido = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCep = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        planodefundolabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar Pedido - TradeTech 1.0");
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel2.setForeground(java.awt.Color.lightGray);
        jLabel2.setText("Cod Pedido:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 70, 30);

        txtPedido.setBackground(new java.awt.Color(18, 18, 20));
        txtPedido.setForeground(new java.awt.Color(204, 204, 204));
        txtPedido.setBorder(null);
        jPanel1.add(txtPedido);
        txtPedido.setBounds(80, 10, 100, 30);

        jButton1.setBackground(new java.awt.Color(3, 62, 11));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(java.awt.SystemColor.control);
        jButton1.setText("Procurar");
        jButton1.setToolTipText("procurar pedido");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(190, 10, 90, 30);

        jLabel3.setForeground(java.awt.Color.lightGray);
        jLabel3.setText("Nome:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 60, 40, 20);

        txtNome.setEditable(false);
        txtNome.setBackground(new java.awt.Color(18, 18, 20));
        txtNome.setForeground(new java.awt.Color(204, 204, 204));
        txtNome.setBorder(null);
        txtNome.setEnabled(false);
        jPanel1.add(txtNome);
        txtNome.setBounds(10, 80, 150, 30);

        jLabel4.setForeground(java.awt.Color.lightGray);
        jLabel4.setText("Telefone:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(230, 60, 60, 20);

        txtTelefone.setEditable(false);
        txtTelefone.setBackground(new java.awt.Color(18, 18, 20));
        txtTelefone.setForeground(new java.awt.Color(204, 204, 204));
        txtTelefone.setBorder(null);
        txtTelefone.setEnabled(false);
        jPanel1.add(txtTelefone);
        txtTelefone.setBounds(230, 80, 120, 30);

        jLabel5.setForeground(java.awt.Color.lightGray);
        jLabel5.setText("Endereço:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(420, 60, 60, 20);

        txtEndereco.setEditable(false);
        txtEndereco.setBackground(new java.awt.Color(18, 18, 20));
        txtEndereco.setForeground(new java.awt.Color(204, 204, 204));
        txtEndereco.setBorder(null);
        txtEndereco.setEnabled(false);
        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });
        jPanel1.add(txtEndereco);
        txtEndereco.setBounds(420, 80, 160, 30);

        jLabel6.setForeground(java.awt.Color.lightGray);
        jLabel6.setText("N:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 120, 20, 20);

        txtNumero.setEditable(false);
        txtNumero.setBackground(new java.awt.Color(18, 18, 20));
        txtNumero.setForeground(new java.awt.Color(204, 204, 204));
        txtNumero.setBorder(null);
        txtNumero.setEnabled(false);
        jPanel1.add(txtNumero);
        txtNumero.setBounds(10, 140, 50, 30);

        jLabel7.setForeground(java.awt.Color.lightGray);
        jLabel7.setText("Bairro:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(230, 120, 40, 20);

        txtBairro.setEditable(false);
        txtBairro.setBackground(new java.awt.Color(18, 18, 20));
        txtBairro.setForeground(new java.awt.Color(204, 204, 204));
        txtBairro.setBorder(null);
        txtBairro.setEnabled(false);
        jPanel1.add(txtBairro);
        txtBairro.setBounds(230, 140, 120, 30);

        jLabel8.setForeground(java.awt.Color.lightGray);
        jLabel8.setText("Cidade:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(420, 120, 50, 20);

        txtCidade.setEditable(false);
        txtCidade.setBackground(new java.awt.Color(18, 18, 20));
        txtCidade.setForeground(new java.awt.Color(204, 204, 204));
        txtCidade.setBorder(null);
        txtCidade.setEnabled(false);
        jPanel1.add(txtCidade);
        txtCidade.setBounds(420, 140, 160, 30);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 182, 600, 10);

        tablePedido.setBackground(java.awt.Color.lightGray);
        tablePedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cod Produto", "Produto", "Qnt Estoque", "Quantidade", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Long.class, java.lang.Long.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePedido.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tablePedido);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(120, 240, 460, 150);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Itens do Pedido");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(240, 200, 130, 20);

        jButton2.setBackground(new java.awt.Color(3, 62, 11));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(java.awt.SystemColor.control);
        jButton2.setText("Sair");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(480, 420, 100, 30);

        btnAdicionar.setBackground(new java.awt.Color(3, 62, 11));
        btnAdicionar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAdicionar.setForeground(java.awt.SystemColor.control);
        btnAdicionar.setText("Adicionar");
        btnAdicionar.setToolTipText("Adicionar Itens");
        btnAdicionar.setBorderPainted(false);
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdicionar);
        btnAdicionar.setBounds(10, 240, 90, 30);

        btnAlterar.setBackground(new java.awt.Color(3, 62, 11));
        btnAlterar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAlterar.setForeground(java.awt.SystemColor.control);
        btnAlterar.setText("Alterar");
        btnAlterar.setToolTipText("Alterar Itens");
        btnAlterar.setBorderPainted(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlterar);
        btnAlterar.setBounds(10, 300, 90, 30);

        btnRemover.setBackground(new java.awt.Color(3, 62, 11));
        btnRemover.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRemover.setForeground(java.awt.SystemColor.control);
        btnRemover.setText("Remover");
        btnRemover.setToolTipText("Remover Itens");
        btnRemover.setBorderPainted(false);
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        jPanel1.add(btnRemover);
        btnRemover.setBounds(10, 360, 90, 30);

        btnConfirmar.setBackground(new java.awt.Color(3, 62, 11));
        btnConfirmar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnConfirmar.setForeground(java.awt.SystemColor.control);
        btnConfirmar.setText("Confirmar");
        btnConfirmar.setBorderPainted(false);
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfirmar);
        btnConfirmar.setBounds(340, 420, 100, 30);

        jLabel10.setForeground(java.awt.Color.lightGray);
        jLabel10.setText("Total a Pagar:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 420, 80, 30);

        txtTotal.setEditable(false);
        txtTotal.setBackground(new java.awt.Color(18, 18, 20));
        txtTotal.setForeground(new java.awt.Color(204, 204, 204));
        txtTotal.setBorder(null);
        jPanel1.add(txtTotal);
        txtTotal.setBounds(90, 420, 80, 30);

        jLabel11.setForeground(java.awt.Color.lightGray);
        jLabel11.setText("CEP:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(80, 120, 40, 20);

        txtCep.setEditable(false);
        txtCep.setBackground(new java.awt.Color(18, 18, 20));
        txtCep.setForeground(new java.awt.Color(204, 204, 204));
        txtCep.setBorder(null);
        txtCep.setEnabled(false);
        jPanel1.add(txtCep);
        txtCep.setBounds(80, 140, 80, 30);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundocliente1.png"))); // NOI18N
        jLabel31.setText("jLabel30");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(0, 0, 600, 470);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 70, 600, 470);

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FotoJet (26).png"))); // NOI18N
        jLabel1.setText("Alteração de Pedido:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 0, 410, 110);

        planodefundolabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/planodefundoapp.png"))); // NOI18N
        planodefundolabel.setText("Fundo");
        getContentPane().add(planodefundolabel);
        planodefundolabel.setBounds(0, 0, 640, 560);

        setSize(new java.awt.Dimension(653, 593));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
       TelaAddItem tela = new TelaAddItem(this,this.tableModel,this.codigoPedido);
       tela.setVisible(true);
       
       this.tableModel = tela.getPedido();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
       TelaAltItem tela = new TelaAltItem(this,this.tableModel);
       tela.setVisible(true);
       
       this.tableModel = tela.getPedido();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
       TelaDelItem tela = new TelaDelItem(this,this.tableModel);
       tela.setVisible(true);
       
       this.tableModel = tela.getPedido();
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(validaConsulta()){
            PedidoDao pedidoDao = new PedidoDao();
            ClienteDao clienteDao = new ClienteDao();
            PedidoTemProdutoDao pedidoTemProdutoDao = new PedidoTemProdutoDao();
            ProdutoDao produtoDao = new ProdutoDao();
            
            pedidoAlterado = pedidoDao.consulta(txtPedido.getText());
            if(pedidoAlterado!=null){
                Cliente cliente = clienteDao.consultaCodigo(pedidoAlterado.getCodigoCliente());
                txtNome.setText(cliente.getNome());
                
                List<PedidoTemProduto> listaItensPedido = pedidoTemProdutoDao.consultaPedido(pedidoAlterado.getCodigo());
                txtTelefone.setText(pedidoAlterado.getTelefone());
                txtBairro.setText(pedidoAlterado.getBairro());
                txtCep.setText(pedidoAlterado.getCep());
                txtCidade.setText(pedidoAlterado.getCidade());
                txtEndereco.setText(pedidoAlterado.getLogradouro());
                txtNumero.setText(String.valueOf(pedidoAlterado.getNumero()));
                setTxtValorTotal(pedidoAlterado.getValor());
                
                for (int i = 0; i < listaItensPedido.size(); i++) {
                    String codigoProduto = String.valueOf(listaItensPedido.get(i).getCodigoProduto());
                    Produto produto = produtoDao.consulta(codigoProduto);
                    
                    listaItensPedido.get(i).setProduto(produto.getNome());
                    listaItensPedido.get(i).setQuantidadeEstoque(produto.getQuantidade());
                }
                
                listaProdutosPedidoNaoAlterado = listaItensPedido;
                tableModel.limpaTabela();
                tableModel.adicionaVariasLinhas(listaItensPedido);
                setTxtValorTotal(tableModel.getValorTotal());
                codigoPedido = pedidoAlterado.getCodigo();
                btnConfirmar.setEnabled(true);
            }else{
                JOptionPane.showMessageDialog(null, "Erro: Pedido não encontrado");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        PedidoDao pedidoDao = new PedidoDao();
        PedidoTemProdutoDao pedidoTemProdutoDao = new PedidoTemProdutoDao();
        
        if(tableModel.getRowCount()>0){
            pedidoAlterado.setValor(valorTotal);
            if(pedidoDao.updade(pedidoAlterado)==1){
                System.out.println('1');
            }
            pedidoTemProdutoDao.excluir(pedidoAlterado.getCodigo());
            if(pedidoTemProdutoDao.salvar(tableModel.getDados())==1){
                System.out.println('2');
            }
            alterarEstoque(tableModel.getDados());
            btnConfirmar.setEnabled(false);
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Erro: Pedido sem produtos");
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void alterarEstoque(List<PedidoTemProduto> produtosDoPedido){
        
        listaProdutosPedidoNaoAlterado.forEach(produtoPedidoNaoAlterado -> {
            boolean status = false;
            for (int i = 0; i < produtosDoPedido.size(); i++) {
                if(produtosDoPedido.get(i).getCodigoProduto()==produtoPedidoNaoAlterado.getCodigoProduto()){
                    status=true;
                }
            }
            if(!status){
                ProdutoDao estoque = new ProdutoDao();
                estoque.updadeEstoque(produtoPedidoNaoAlterado.getCodigoProduto(), produtoPedidoNaoAlterado.getQuantidadeEstoque()+produtoPedidoNaoAlterado.getQuantidade());
                estoque.desconectar();
            }
        });
        
        produtosDoPedido.forEach(produtoPedido->{
            ProdutoDao estoque = new ProdutoDao();
            estoque.updadeEstoque(produtoPedido.getCodigoProduto(), produtoPedido.getQuantidadeEstoque());
        });
    }
    
    public void setValorTotal(double valorTotal) {
        
        this.valorTotal = valorTotal;
        setTxtValorTotal(valorTotal);
    }

    private boolean validaConsulta() {
        if (txtPedido.getText().length()>=1) {
            return true;
        }
        JOptionPane.showMessageDialog(null, "Erro: Pedido invalido");
        txtPedido.requestFocus();
        return false;
    }
    
    private void setTxtValorTotal(double valor){
        txtTotal.setText(String.valueOf(valor));
//        txtTotal.setText(String.valueOf(valor).replace(".", ","));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAltPed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAltPed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAltPed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAltPed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAltPed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel planodefundolabel;
    private javax.swing.JTable tablePedido;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPedido;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
