/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual.pedidos;

import data.cliente.ClienteDao;
import data.cliente.Fisico;
import data.cliente.Juridico;
import data.pedido.Pedido;
import data.pedido.PedidoDao;
import data.pedidoTemProduto.PedidoTemProdutoTableModel;
import data.pedidoTemProduto.PedidoTemProduto;
import data.pedidoTemProduto.PedidoTemProdutoDao;
import data.produto.ProdutoDao;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Nelson
 */
public class TelaNewPed extends javax.swing.JFrame {

    /**
     * Creates new form TelaNewPed
     */
    private int codigoCliente;
    private PedidoDao pedidoDao = new PedidoDao();
    private PedidoTemProdutoDao pedidoTemProdutoDao = new PedidoTemProdutoDao();
    private String entrega = "s";
    private PedidoTemProdutoTableModel tableModel = new PedidoTemProdutoTableModel();
    private List<PedidoTemProduto> pedidoTemProdutoDados;
    private int codigoPedido;
    private double valorTotal = 0;

    public TelaNewPed() {
        initComponents();

        btnSim.setSelected(true);
        btnNão.setSelected(false);
        codigoPedido = pedidoDao.consultaProximoCodigo();
        txtCodigoPedido.setText(String.valueOf(codigoPedido));
        tablePedido.setModel(tableModel);
        setTxtValorTotal(valorTotal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCpfCnpj = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSim = new javax.swing.JRadioButton();
        btnNão = new javax.swing.JRadioButton();
        txtEndereco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCodigoPedido = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePedido = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtTotalPagar = new javax.swing.JFormattedTextField();
        txtNumero = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtCep = new javax.swing.JFormattedTextField();
        txtTelefone = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        planodefundolabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novo Pedido - TradeTech 1.0");
        setResizable(false);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel2.setForeground(java.awt.Color.lightGray);
        jLabel2.setText("Informe o CPF/CNPJ do Cliente:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 160, 30);

        txtCpfCnpj.setBackground(new java.awt.Color(18, 18, 20));
        txtCpfCnpj.setForeground(new java.awt.Color(204, 204, 204));
        txtCpfCnpj.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCpfCnpj.setBorder(null);
        txtCpfCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfCnpjActionPerformed(evt);
            }
        });
        jPanel1.add(txtCpfCnpj);
        txtCpfCnpj.setBounds(170, 10, 100, 30);

        btnConsultar.setBackground(new java.awt.Color(3, 62, 11));
        btnConsultar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnConsultar.setForeground(java.awt.SystemColor.control);
        btnConsultar.setText("Consultar");
        btnConsultar.setBorderPainted(false);
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultar);
        btnConsultar.setBounds(280, 10, 90, 30);

        jLabel3.setForeground(java.awt.Color.lightGray);
        jLabel3.setText("Nome:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(400, 10, 40, 30);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(10, 150, 700, 10);

        txtNome.setEditable(false);
        txtNome.setBackground(new java.awt.Color(18, 18, 20));
        txtNome.setForeground(new java.awt.Color(204, 204, 204));
        txtNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNome.setBorder(null);
        jPanel1.add(txtNome);
        txtNome.setBounds(440, 10, 260, 30);

        jLabel4.setForeground(java.awt.Color.lightGray);
        jLabel4.setText("Endereço:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 100, 60, 30);

        jLabel5.setForeground(java.awt.Color.lightGray);
        jLabel5.setText("Pedido para Entrega?");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 60, 120, 20);

        btnSim.setForeground(java.awt.Color.lightGray);
        btnSim.setText("Sim");
        btnSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimActionPerformed(evt);
            }
        });
        jPanel1.add(btnSim);
        btnSim.setBounds(140, 60, 50, 23);

        btnNão.setForeground(java.awt.Color.lightGray);
        btnNão.setText("Não");
        btnNão.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNãoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNão);
        btnNão.setBounds(190, 60, 50, 23);

        txtEndereco.setBackground(new java.awt.Color(18, 18, 20));
        txtEndereco.setForeground(new java.awt.Color(204, 204, 204));
        txtEndereco.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEndereco.setBorder(null);
        jPanel1.add(txtEndereco);
        txtEndereco.setBounds(70, 100, 190, 30);

        jLabel6.setForeground(java.awt.Color.lightGray);
        jLabel6.setText("N:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(280, 100, 20, 30);

        txtCodigoPedido.setEditable(false);
        txtCodigoPedido.setBackground(new java.awt.Color(18, 18, 20));
        txtCodigoPedido.setForeground(new java.awt.Color(204, 204, 204));
        txtCodigoPedido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigoPedido.setBorder(null);
        txtCodigoPedido.setEnabled(false);
        jPanel1.add(txtCodigoPedido);
        txtCodigoPedido.setBounds(630, 330, 60, 30);

        jLabel7.setForeground(java.awt.Color.lightGray);
        jLabel7.setText("CEP:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(520, 50, 30, 30);

        txtBairro.setBackground(new java.awt.Color(18, 18, 20));
        txtBairro.setForeground(new java.awt.Color(204, 204, 204));
        txtBairro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBairro.setBorder(null);
        jPanel1.add(txtBairro);
        txtBairro.setBounds(420, 100, 80, 30);

        jLabel8.setForeground(java.awt.Color.lightGray);
        jLabel8.setText("Cidade:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(520, 100, 50, 30);

        txtCidade.setBackground(new java.awt.Color(18, 18, 20));
        txtCidade.setForeground(new java.awt.Color(204, 204, 204));
        txtCidade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCidade.setBorder(null);
        jPanel1.add(txtCidade);
        txtCidade.setBounds(570, 100, 130, 30);

        tablePedido.setBackground(java.awt.Color.lightGray);
        tablePedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cod Produto", "Produto", "Qnt Estoque", "Quantidade", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Long.class, java.lang.Long.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePedido.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tablePedido);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(230, 200, 460, 110);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(java.awt.Color.lightGray);
        jLabel9.setText("Itens do Pedido");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(390, 170, 110, 20);

        btnAdicionar.setBackground(new java.awt.Color(3, 62, 11));
        btnAdicionar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAdicionar.setForeground(java.awt.SystemColor.control);
        btnAdicionar.setText("Adicionar");
        btnAdicionar.setToolTipText("Adicionar Itens");
        btnAdicionar.setBorderPainted(false);
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdicionar);
        btnAdicionar.setBounds(70, 200, 90, 30);

        btnEditar.setBackground(new java.awt.Color(3, 62, 11));
        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEditar.setForeground(java.awt.SystemColor.control);
        btnEditar.setText("Editar");
        btnEditar.setToolTipText("Editar Itens");
        btnEditar.setBorderPainted(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar);
        btnEditar.setBounds(70, 240, 90, 30);

        btnRemover.setBackground(new java.awt.Color(3, 62, 11));
        btnRemover.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRemover.setForeground(java.awt.SystemColor.control);
        btnRemover.setText("Remover");
        btnRemover.setToolTipText("Remover Itens");
        btnRemover.setBorderPainted(false);
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        jPanel1.add(btnRemover);
        btnRemover.setBounds(70, 280, 90, 30);

        btnConfirmar.setBackground(new java.awt.Color(3, 62, 11));
        btnConfirmar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnConfirmar.setForeground(java.awt.SystemColor.control);
        btnConfirmar.setText("Confirmar");
        btnConfirmar.setBorderPainted(false);
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfirmar);
        btnConfirmar.setBounds(580, 380, 110, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(java.awt.Color.lightGray);
        jLabel10.setText("Cod Pedido:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(550, 330, 80, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(java.awt.Color.lightGray);
        jLabel13.setText("Total a pagar:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(340, 380, 80, 30);

        txtTotalPagar.setEditable(false);
        txtTotalPagar.setBackground(new java.awt.Color(18, 18, 20));
        txtTotalPagar.setBorder(null);
        txtTotalPagar.setForeground(new java.awt.Color(204, 204, 204));
        txtTotalPagar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        txtTotalPagar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtTotalPagar);
        txtTotalPagar.setBounds(430, 380, 90, 30);

        txtNumero.setBackground(new java.awt.Color(18, 18, 20));
        txtNumero.setForeground(new java.awt.Color(204, 204, 204));
        txtNumero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumero.setBorder(null);
        jPanel1.add(txtNumero);
        txtNumero.setBounds(300, 100, 60, 30);

        jLabel14.setForeground(java.awt.Color.lightGray);
        jLabel14.setText("Bairro:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(380, 100, 40, 30);

        jLabel15.setForeground(java.awt.Color.lightGray);
        jLabel15.setText("Telefone:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(290, 50, 60, 30);

        txtCep.setBackground(new java.awt.Color(18, 18, 20));
        txtCep.setBorder(null);
        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCep.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtCep);
        txtCep.setBounds(570, 50, 100, 30);

        txtTelefone.setBackground(new java.awt.Color(18, 18, 20));
        txtTelefone.setBorder(null);
        jPanel1.add(txtTelefone);
        txtTelefone.setBounds(350, 50, 130, 30);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundocliente1.png"))); // NOI18N
        jLabel31.setText("jLabel30");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(0, 0, 710, 430);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 80, 710, 430);

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FotoJet (29).png"))); // NOI18N
        jLabel1.setText("Novo Pedido:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 20, 420, 80);

        planodefundolabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/planodefundoapp.png"))); // NOI18N
        planodefundolabel.setText("Fundo");
        getContentPane().add(planodefundolabel);
        planodefundolabel.setBounds(0, 0, 770, 560);

        setSize(new java.awt.Dimension(785, 569));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCpfCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfCnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfCnpjActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        TelaAddItem tela = new TelaAddItem(this,this.tableModel, this.codigoPedido);
        tela.setVisible(true);
        
        this.tableModel = tela.getPedido();
        this.pedidoTemProdutoDados = tela.getPedido().getDados();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        TelaAltItem tela = new TelaAltItem(this,this.tableModel);
        tela.setVisible(true);
        
        this.tableModel = tela.getPedido();
        this.pedidoTemProdutoDados = tela.getPedido().getDados();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        TelaDelItem tela = new TelaDelItem(this,this.tableModel);
        tela.setVisible(true);
        
        this.tableModel = tela.getPedido();
        this.pedidoTemProdutoDados = tela.getPedido().getDados();
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        ClienteDao clienteDao = new ClienteDao();
        if (validaConsulta()) {
            String consulta = txtCpfCnpj.getText();
            if (consulta.length() == 11) {
                Fisico cliente = clienteDao.consultaFisico(consulta);
                if (cliente != null) {
                    txtNome.setText(cliente.getNome());
                    codigoCliente = cliente.getCodigoCliente();
                } else {
                    JOptionPane.showMessageDialog(null, "Erro: Cliente não encontrado");
                    txtCpfCnpj.requestFocus();
                }
            } else {
                Juridico cliente = clienteDao.consultaJuridico(consulta);
                if (cliente != null) {
                    txtNome.setText(cliente.getNome());
                    codigoCliente = Integer.parseInt(consulta);
                } else {
                    JOptionPane.showMessageDialog(null, "Erro: Cliente não encontrado");
                    txtCpfCnpj.requestFocus();
                }
            }
        }
        clienteDao.desconectar();
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimActionPerformed
        btnSim.setSelected(true);
        btnNão.setSelected(false);

        txtTelefone.setEnabled(true);
        txtCep.setEnabled(true);
        txtCidade.setEnabled(true);
        txtBairro.setEnabled(true);
        txtEndereco.setEnabled(true);
        txtNumero.setEnabled(true);
        entrega="S";
    }//GEN-LAST:event_btnSimActionPerformed

    private void btnNãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNãoActionPerformed
        
        btnNão.setSelected(false);
        JOptionPane.showMessageDialog(null, "Erro: ainda não esta funcionando");
//        btnNão.setSelected(true);
//        btnSim.setSelected(false);
//
//        txtTelefone.setEnabled(false);
//        txtCep.setEnabled(false);
//        txtCidade.setEnabled(false);
//        txtBairro.setEnabled(false);
//        txtEndereco.setEnabled(false);
//        txtNumero.setEnabled(false);
//        entrega="N";
    }//GEN-LAST:event_btnNãoActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        if(validaCampos()){
            Pedido pedido = new Pedido();
            pedido.setCodigo(codigoPedido);
            pedido.setTelefone(txtTelefone.getText());
            pedido.setCep(txtCep.getText());
            pedido.setBairro(txtBairro.getText());
            pedido.setEntrega(entrega);
            pedido.setLogradouro(txtEndereco.getText());
            pedido.setCidade(txtCidade.getText());
            pedido.setNumero(Integer.parseInt(txtNumero.getText()));
            pedido.setCodigoCliente(codigoCliente);
            pedido.setValor(tableModel.getValorTotal());
            if(pedidoDao.salvar(pedido)==1){
                alterarEstoque(pedidoTemProdutoDados);
                if(pedidoTemProdutoDao.salvar(pedidoTemProdutoDados)!=1){
                    JOptionPane.showMessageDialog(null, "Erro ao salvar pedido");
                    pedidoTemProdutoDao.excluir(codigoPedido);
                    pedidoDao.excluir(codigoPedido);
                }else{
                    JOptionPane.showMessageDialog(null, "Pedido realizado com sucesso");
                    dispose();
                }
            }else{
                JOptionPane.showMessageDialog(null, "Erro ao salvar pedido");
            }
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
//        valorTotal = tableModel.getValorTotal();
//        setTxtValorTotal(valorTotal);
    }//GEN-LAST:event_formFocusGained
  
    private void alterarEstoque(List<PedidoTemProduto> produtosDoPedido){
        produtosDoPedido.forEach(produtoDoPedido -> {
            ProdutoDao estoque = new ProdutoDao();
            estoque.updadeEstoque(produtoDoPedido.getCodigoProduto(), produtoDoPedido.getQuantidadeEstoque()-produtoDoPedido.getQuantidade());
        });
    }
    
    public void setValorTotal(double valorTotal) {
        
        this.valorTotal = valorTotal;
        setTxtValorTotal(valorTotal);
    }
    
    private void setTxtValorTotal(double valor){
        txtTotalPagar.setText(String.valueOf(valor).replace(".", ","));
    }
    
    private boolean validaConsulta() {
        if (txtCpfCnpj.getText().length() == 11 || txtCpfCnpj.getText().length() == 14) {
            return true;
        }
        JOptionPane.showMessageDialog(null, "Erro: CPF/CNPJ invalido");
        txtCpfCnpj.requestFocus();
        return false;
    }

    private boolean validaCampos() {
        if (txtTelefone.getText().length() < 8 && btnSim.isSelected()) {
            JOptionPane.showMessageDialog(null, "Erro: Telefone invalido");
            txtTelefone.requestFocus();
            return false;
        } else if (txtCep.getText().equals("     -   ") && btnSim.isSelected()) {
            JOptionPane.showMessageDialog(null, "Erro: Cep invalido");
            txtCep.requestFocus();
            return false;
        } else if (txtEndereco.getText().length() < 2 && btnSim.isSelected()) {
            JOptionPane.showMessageDialog(null, "Erro: Endereco invalido");
            txtEndereco.requestFocus();
            return false;
        } else if (txtBairro.getText().length() < 1 && btnSim.isSelected()) {
            JOptionPane.showMessageDialog(null, "Erro: Bairro invalido");
            txtBairro.requestFocus();
            return false;
        } else if (txtCidade.getText().length() < 2 && btnSim.isSelected()) {
            JOptionPane.showMessageDialog(null, "Erro: Cidade invalido");
            txtCidade.requestFocus();
            return false;
        } else if (tableModel.getRowCount()<=0) {
            JOptionPane.showMessageDialog(null, "Erro: Necessario pelo menos um pedido");
            return false;
        } else {
            int numero;
            try {
                numero = Integer.parseInt(txtNumero.getText());
            } catch (NumberFormatException e) {
                numero = 0;
            }
            if ((numero <= 0 || numero > 20000) && btnSim.isSelected()) {
                JOptionPane.showMessageDialog(null, "Erro: Numero invalido");
                txtNumero.requestFocus();
                return false;
            }
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaNewPed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaNewPed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaNewPed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNewPed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaNewPed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JRadioButton btnNão;
    private javax.swing.JButton btnRemover;
    private javax.swing.JRadioButton btnSim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel planodefundolabel;
    private javax.swing.JTable tablePedido;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCodigoPedido;
    private javax.swing.JTextField txtCpfCnpj;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JFormattedTextField txtTotalPagar;
    // End of variables declaration//GEN-END:variables
}
