/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual.pedidos;

import data.pedidoTemProduto.PedidoTemProdutoTableModel;
import data.pedidoTemProduto.PedidoTemProduto;
import javax.swing.JOptionPane;

/**
 *
 * @author Nelson
 */
public class TelaDelItem extends javax.swing.JFrame {

    /**
     * Creates new form TelaDelItem
     */
    
    private PedidoTemProdutoTableModel pedido;
    private PedidoTemProduto pedidoTemProduto;
    private TelaAltPed telaAltPed = null;
    private TelaNewPed telaNewPed = null;

    public PedidoTemProdutoTableModel getPedido() {
        return pedido;
    }
    
    public TelaDelItem(TelaAltPed telaAltPed,PedidoTemProdutoTableModel pedido) {
        initComponents();
        
        this.pedido = pedido;
        tablePedido.setModel(pedido);
        btnExcluir.setEnabled(false);
        
        this.telaAltPed = telaAltPed;
    }
    
    public TelaDelItem(TelaNewPed telaNewPed,PedidoTemProdutoTableModel pedido) {
        initComponents();
        
        this.pedido = pedido;
        tablePedido.setModel(pedido);
        btnExcluir.setEnabled(false);
        
        this.telaNewPed = telaNewPed;
    }
    
    public TelaDelItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtConsulta = new javax.swing.JTextField();
        btnProcurar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePedido = new javax.swing.JTable();
        jLabel31 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        planodefundolabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Remover Item - TradeTech 1.0");
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel2.setForeground(java.awt.Color.lightGray);
        jLabel2.setText("Cod do Produto:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 20, 90, 30);

        txtConsulta.setBackground(new java.awt.Color(18, 18, 20));
        txtConsulta.setForeground(new java.awt.Color(204, 204, 204));
        txtConsulta.setBorder(null);
        jPanel1.add(txtConsulta);
        txtConsulta.setBounds(120, 20, 100, 30);

        btnProcurar.setBackground(new java.awt.Color(3, 62, 11));
        btnProcurar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnProcurar.setForeground(java.awt.SystemColor.control);
        btnProcurar.setText("Procurar");
        btnProcurar.setToolTipText("Adicionar produto");
        btnProcurar.setBorderPainted(false);
        btnProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarActionPerformed(evt);
            }
        });
        jPanel1.add(btnProcurar);
        btnProcurar.setBounds(230, 20, 90, 30);

        jLabel3.setForeground(java.awt.Color.lightGray);
        jLabel3.setText("Produto:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 70, 50, 20);

        txtProduto.setEditable(false);
        txtProduto.setBackground(new java.awt.Color(18, 18, 20));
        txtProduto.setForeground(new java.awt.Color(204, 204, 204));
        txtProduto.setBorder(null);
        jPanel1.add(txtProduto);
        txtProduto.setBounds(30, 90, 130, 30);

        jLabel4.setForeground(java.awt.Color.lightGray);
        jLabel4.setText("Quantidade:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(200, 70, 70, 20);

        txtQuantidade.setBackground(new java.awt.Color(18, 18, 20));
        txtQuantidade.setForeground(new java.awt.Color(204, 204, 204));
        txtQuantidade.setBorder(null);
        jPanel1.add(txtQuantidade);
        txtQuantidade.setBounds(200, 90, 80, 30);

        jLabel5.setForeground(java.awt.Color.lightGray);
        jLabel5.setText("Valor:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(320, 70, 28, 20);

        txtValor.setEditable(false);
        txtValor.setBackground(new java.awt.Color(18, 18, 20));
        txtValor.setForeground(new java.awt.Color(204, 204, 204));
        txtValor.setBorder(null);
        jPanel1.add(txtValor);
        txtValor.setBounds(320, 90, 90, 30);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 140, 580, 10);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Itens do Pedido");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(230, 150, 150, 30);

        btnExcluir.setBackground(new java.awt.Color(3, 62, 11));
        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnExcluir.setForeground(java.awt.SystemColor.control);
        btnExcluir.setText("Excluir Item");
        btnExcluir.setBorderPainted(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btnExcluir);
        btnExcluir.setBounds(460, 90, 110, 30);

        tablePedido.setBackground(java.awt.Color.lightGray);
        tablePedido.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tablePedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cod Produto", "Produto", "Qtd Estoque", "Quantidade", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Object.class, java.lang.Double.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablePedido);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 190, 540, 180);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundocliente1.png"))); // NOI18N
        jLabel31.setText("jLabel30");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(0, 0, 600, 470);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 70, 580, 390);

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FotoJet (27).png"))); // NOI18N
        jLabel1.setText("Remover Item:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 420, 80);

        jButton3.setBackground(new java.awt.Color(3, 62, 11));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setForeground(java.awt.SystemColor.control);
        jButton3.setText("OK");
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(490, 480, 110, 40);

        planodefundolabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/planodefundoapp.png"))); // NOI18N
        planodefundolabel.setText("Fundo");
        getContentPane().add(planodefundolabel);
        planodefundolabel.setBounds(0, 0, 640, 560);

        setSize(new java.awt.Dimension(649, 574));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarActionPerformed
        if(validaConsulta()){
            pedidoTemProduto = pedido.consulta(Integer.parseInt(txtConsulta.getText()));
            if(pedidoTemProduto!=null){
                txtProduto.setText(pedidoTemProduto.getProduto());
                txtQuantidade.setText(String.valueOf(pedidoTemProduto.getQuantidade()));
                txtValor.setText(String.valueOf(pedidoTemProduto.getValor()));
                
                btnExcluir.setEnabled(true);
            }else{
                txtConsulta.requestFocus();
                JOptionPane.showMessageDialog(null, "Erro: Codigo invalido");
            }
        }
    }//GEN-LAST:event_btnProcurarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        pedido.removerProduto(pedidoTemProduto.getCodigoProduto());
        
                
        if(telaAltPed!=null){
            telaAltPed.setValorTotal(pedido.getValorTotal());
        }
        
        btnExcluir.setEnabled(false);
    }//GEN-LAST:event_btnExcluirActionPerformed
    
    private boolean validaConsulta(){
        if(txtConsulta.getText().length()>=1){
            return true;
        }
        txtConsulta.requestFocus();
        JOptionPane.showMessageDialog(null, "Erro: Codigo invalido");
        return false;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDelItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDelItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDelItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDelItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDelItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnProcurar;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel planodefundolabel;
    private javax.swing.JTable tablePedido;
    private javax.swing.JTextField txtConsulta;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
