/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual.telaprincipal;

import visual.login.TelaLogin;
import data.funcionario.Funcionario;
import data.funcionario.FuncionarioDao;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import visual.cadastros.TelaCadCliente;
import visual.cadastros.TelaCadEntrega;
import visual.cadastros.TelaCadFunc;
import visual.cadastros.TelaCadProd;
import visual.consultas.TelaEstq;
import visual.pedidos.TelaNewPed;
import visual.consultas.TelaRelCliente;
import visual.consultas.TelaRelFunc;
import visual.entrega.TelaAltEntrega;
import visual.entrega.TelaDelEntrega;
import visual.entrega.TelaEnvEntrega;
import visual.entrega.TelaRelEntrega;
import visual.pedidos.TelaAltPed;
import visual.pedidos.TelaDelPed;
import visual.pedidos.TelaRelPedido;

/**
 *
 * @author Nelson
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal(String ra) {
        initComponents();
        FuncionarioDao funcionarioDao = new FuncionarioDao();
        Funcionario funcionario = funcionarioDao.consulta(ra);
        if(funcionario!=null){
            txtCargo.setText(funcionario.getCargo());
            txtFuncionario.setText(funcionario.getNome());
        }else{
            JOptionPane.showMessageDialog(null,"Erro: Favor se logar novamente");
            TelaLogin telaLogin = new TelaLogin();
            telaLogin.setVisible(true);
            dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jPanelBotoes = new javax.swing.JPanel();
        jButtonCadcliente = new javax.swing.JButton();
        jButtonCadFunc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonCadProd = new javax.swing.JButton();
        jButtonCadEnt = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButtonRelCliente = new javax.swing.JButton();
        jButtonRelFunc = new javax.swing.JButton();
        jButtonRelEstoq = new javax.swing.JButton();
        jButtonRelEnt = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanelPedidos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jButtonNewPed = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanelEntrega = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        log = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtFuncionario = new javax.swing.JTextField();
        txtCargo = new javax.swing.JTextField();
        txtData = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem26 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenu7.setText("jMenu7");

        jMenu8.setText("jMenu8");

        jMenu9.setText("jMenu9");

        jMenuItem5.setText("jMenuItem5");

        jMenuItem6.setText("jMenuItem6");

        jMenuItem7.setText("jMenuItem7");

        jMenuItem8.setText("jMenuItem8");

        jMenuItem9.setText("jMenuItem9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Painel Principal - TradeTech 1.0");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanelBotoes.setToolTipText("Painel de Cadastros");
        jPanelBotoes.setOpaque(false);
        jPanelBotoes.setLayout(null);

        jButtonCadcliente.setBackground(new java.awt.Color(18, 18, 20));
        jButtonCadcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/addfunc.png"))); // NOI18N
        jButtonCadcliente.setToolTipText("Cadastro de Clientes");
        jButtonCadcliente.setBorder(null);
        jButtonCadcliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonCadcliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCadcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadclienteActionPerformed(evt);
            }
        });
        jPanelBotoes.add(jButtonCadcliente);
        jButtonCadcliente.setBounds(100, 60, 80, 60);

        jButtonCadFunc.setBackground(new java.awt.Color(18, 18, 20));
        jButtonCadFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/addcli.png"))); // NOI18N
        jButtonCadFunc.setToolTipText("Cadastro de Funcionarios");
        jButtonCadFunc.setBorder(null);
        jButtonCadFunc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonCadFunc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadFuncActionPerformed(evt);
            }
        });
        jPanelBotoes.add(jButtonCadFunc);
        jButtonCadFunc.setBounds(10, 60, 80, 60);

        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastros (2).png"))); // NOI18N
        jLabel1.setText("Cadastros:");
        jPanelBotoes.add(jLabel1);
        jLabel1.setBounds(-30, 0, 190, 60);

        jButtonCadProd.setBackground(new java.awt.Color(18, 18, 20));
        jButtonCadProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/addproduto.png"))); // NOI18N
        jButtonCadProd.setToolTipText("Cadastro de Produtos");
        jButtonCadProd.setBorder(null);
        jButtonCadProd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonCadProd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCadProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadProdActionPerformed(evt);
            }
        });
        jPanelBotoes.add(jButtonCadProd);
        jButtonCadProd.setBounds(100, 160, 80, 60);

        jButtonCadEnt.setBackground(new java.awt.Color(18, 18, 20));
        jButtonCadEnt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/addentrega.png"))); // NOI18N
        jButtonCadEnt.setToolTipText("Cadastro de Entrega");
        jButtonCadEnt.setBorder(null);
        jButtonCadEnt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonCadEnt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCadEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadEntActionPerformed(evt);
            }
        });
        jPanelBotoes.add(jButtonCadEnt);
        jButtonCadEnt.setBounds(10, 160, 80, 60);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(java.awt.Color.lightGray);
        jLabel10.setText("Clientes");
        jPanelBotoes.add(jLabel10);
        jLabel10.setBounds(115, 40, 50, 14);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(java.awt.Color.lightGray);
        jLabel12.setText("Produtos");
        jPanelBotoes.add(jLabel12);
        jLabel12.setBounds(110, 140, 60, 14);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(java.awt.Color.lightGray);
        jLabel11.setText("Entrega");
        jPanelBotoes.add(jLabel11);
        jLabel11.setBounds(30, 140, 44, 14);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(java.awt.Color.lightGray);
        jLabel9.setText("Funcionarios");
        jPanelBotoes.add(jLabel9);
        jLabel9.setBounds(15, 40, 80, 14);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoTelaPrincipal.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanelBotoes.add(jLabel8);
        jLabel8.setBounds(0, 0, 200, 250);

        getContentPane().add(jPanelBotoes);
        jPanelBotoes.setBounds(20, 290, 190, 250);

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logoT.png"))); // NOI18N
        jLabel33.setText("jLabel33");
        getContentPane().add(jLabel33);
        jLabel33.setBounds(20, 70, 90, 50);

        jPanel2.setToolTipText("Painel de Relatórios");
        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/consultas.png"))); // NOI18N
        jLabel2.setText("Consultas:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(-30, 10, 190, 40);

        jButtonRelCliente.setBackground(new java.awt.Color(18, 18, 20));
        jButtonRelCliente.setForeground(new java.awt.Color(18, 18, 20));
        jButtonRelCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-chamada-em-conferência-50 (1).png"))); // NOI18N
        jButtonRelCliente.setBorderPainted(false);
        jButtonRelCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonRelCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRelCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelClienteActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonRelCliente);
        jButtonRelCliente.setBounds(10, 60, 80, 60);

        jButtonRelFunc.setBackground(new java.awt.Color(18, 18, 20));
        jButtonRelFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-gestão-de-desenvolvimento-comercial-50.png"))); // NOI18N
        jButtonRelFunc.setBorderPainted(false);
        jButtonRelFunc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonRelFunc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRelFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelFuncActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonRelFunc);
        jButtonRelFunc.setBounds(100, 60, 80, 60);

        jButtonRelEstoq.setBackground(new java.awt.Color(18, 18, 20));
        jButtonRelEstoq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-armazém-64.png"))); // NOI18N
        jButtonRelEstoq.setBorderPainted(false);
        jButtonRelEstoq.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonRelEstoq.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRelEstoq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelEstoqActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonRelEstoq);
        jButtonRelEstoq.setBounds(10, 160, 80, 60);

        jButtonRelEnt.setBackground(new java.awt.Color(18, 18, 20));
        jButtonRelEnt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-caminhão-50 (1).png"))); // NOI18N
        jButtonRelEnt.setBorderPainted(false);
        jButtonRelEnt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonRelEnt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRelEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelEntActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonRelEnt);
        jButtonRelEnt.setBounds(100, 160, 80, 60);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(java.awt.Color.lightGray);
        jLabel14.setText("Clientes");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(30, 40, 45, 14);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(java.awt.Color.lightGray);
        jLabel15.setText("Funcionarios");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(105, 40, 71, 14);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setForeground(java.awt.Color.lightGray);
        jLabel16.setText("Estoque");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(30, 140, 45, 14);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setForeground(java.awt.Color.lightGray);
        jLabel17.setText("Entregas");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(115, 140, 50, 14);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoTelaPrincipal.png"))); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(0, -30, 190, 310);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel32.setForeground(java.awt.Color.lightGray);
        jLabel32.setText("Entregas");
        jPanel2.add(jLabel32);
        jLabel32.setBounds(115, 140, 50, 14);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(220, 290, 190, 250);
        jPanel2.getAccessibleContext().setAccessibleName("");

        jPanelPedidos.setToolTipText("Consulta de Pedidos");
        jPanelPedidos.setOpaque(false);
        jPanelPedidos.setLayout(null);

        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pedidos.png"))); // NOI18N
        jLabel3.setText("Pedidos:");
        jPanelPedidos.add(jLabel3);
        jLabel3.setBounds(-30, 10, 180, 40);

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel38.setForeground(java.awt.Color.lightGray);
        jLabel38.setText("Cancelar");
        jPanelPedidos.add(jLabel38);
        jLabel38.setBounds(20, 140, 50, 20);

        jButtonNewPed.setBackground(new java.awt.Color(18, 18, 20));
        jButtonNewPed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/addpedido.png"))); // NOI18N
        jButtonNewPed.setBorderPainted(false);
        jButtonNewPed.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonNewPed.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNewPed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewPedActionPerformed(evt);
            }
        });
        jPanelPedidos.add(jButtonNewPed);
        jButtonNewPed.setBounds(10, 60, 80, 60);

        jButton8.setBackground(new java.awt.Color(18, 18, 20));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novopedido.png"))); // NOI18N
        jButton8.setBorderPainted(false);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanelPedidos.add(jButton8);
        jButton8.setBounds(100, 60, 80, 60);

        jButton10.setBackground(new java.awt.Color(18, 18, 20));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendaspedido.png"))); // NOI18N
        jButton10.setBorderPainted(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanelPedidos.add(jButton10);
        jButton10.setBounds(100, 160, 80, 60);

        jButton13.setBackground(new java.awt.Color(18, 18, 20));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelpedido.png"))); // NOI18N
        jButton13.setBorderPainted(false);
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanelPedidos.add(jButton13);
        jButton13.setBounds(10, 160, 80, 60);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setForeground(java.awt.Color.lightGray);
        jLabel19.setText("Alt/Pedido");
        jPanelPedidos.add(jLabel19);
        jLabel19.setBounds(110, 40, 60, 14);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setForeground(java.awt.Color.lightGray);
        jLabel20.setText("Novo Pedido");
        jPanelPedidos.add(jLabel20);
        jLabel20.setBounds(15, 40, 69, 14);

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel39.setForeground(java.awt.Color.lightGray);
        jLabel39.setText("Vendas");
        jPanelPedidos.add(jLabel39);
        jLabel39.setBounds(120, 140, 50, 14);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoTelaPrincipal.png"))); // NOI18N
        jLabel18.setText("jLabel18");
        jPanelPedidos.add(jLabel18);
        jLabel18.setBounds(0, 0, 190, 250);

        getContentPane().add(jPanelPedidos);
        jPanelPedidos.setBounds(420, 290, 190, 250);

        jPanelEntrega.setToolTipText("Painel de Entregas");
        jPanelEntrega.setOpaque(false);
        jPanelEntrega.setLayout(null);

        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/entregas.png"))); // NOI18N
        jLabel4.setText("Entrega:");
        jPanelEntrega.add(jLabel4);
        jLabel4.setBounds(-30, 10, 180, 40);

        jButton11.setBackground(new java.awt.Color(18, 18, 20));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/enviarentregas.png"))); // NOI18N
        jButton11.setBorderPainted(false);
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanelEntrega.add(jButton11);
        jButton11.setBounds(10, 60, 80, 60);

        jButton12.setBackground(new java.awt.Color(18, 18, 20));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editentregas.png"))); // NOI18N
        jButton12.setBorderPainted(false);
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanelEntrega.add(jButton12);
        jButton12.setBounds(100, 60, 80, 60);

        jButton14.setBackground(new java.awt.Color(18, 18, 20));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorio.png"))); // NOI18N
        jButton14.setBorderPainted(false);
        jButton14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanelEntrega.add(jButton14);
        jButton14.setBounds(100, 160, 80, 60);

        jButton9.setBackground(new java.awt.Color(18, 18, 20));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelentregas.png"))); // NOI18N
        jButton9.setBorderPainted(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanelEntrega.add(jButton9);
        jButton9.setBounds(10, 160, 80, 60);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setForeground(java.awt.Color.lightGray);
        jLabel22.setText("Alterar");
        jPanelEntrega.add(jLabel22);
        jLabel22.setBounds(120, 40, 40, 14);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setForeground(java.awt.Color.lightGray);
        jLabel23.setText("Relatorio");
        jPanelEntrega.add(jLabel23);
        jLabel23.setBounds(120, 140, 60, 14);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setForeground(java.awt.Color.lightGray);
        jLabel24.setText("Enviar");
        jPanelEntrega.add(jLabel24);
        jLabel24.setBounds(32, 40, 35, 14);

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel40.setForeground(java.awt.Color.lightGray);
        jLabel40.setText("Cancelar");
        jPanelEntrega.add(jLabel40);
        jLabel40.setBounds(25, 140, 49, 14);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoTelaPrincipal.png"))); // NOI18N
        jLabel21.setText("jLabel21");
        jPanelEntrega.add(jLabel21);
        jLabel21.setBounds(0, 0, 190, 250);

        getContentPane().add(jPanelEntrega);
        jPanelEntrega.setBounds(620, 290, 190, 250);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/acessorios.png"))); // NOI18N
        jLabel5.setText("Acessorios:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(-30, 10, 180, 40);

        jButton16.setBackground(new java.awt.Color(18, 18, 20));
        jButton16.setForeground(new java.awt.Color(18, 18, 20));
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/calendario1.png"))); // NOI18N
        jButton16.setBorderPainted(false);
        jButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jButton16);
        jButton16.setBounds(100, 60, 80, 60);

        jButton17.setBackground(new java.awt.Color(18, 18, 20));
        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-símbolo-nulo-50.png"))); // NOI18N
        jButton17.setBorderPainted(false);
        jPanel1.add(jButton17);
        jButton17.setBounds(10, 160, 80, 60);

        jButton18.setBackground(new java.awt.Color(18, 18, 20));
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-símbolo-nulo-50.png"))); // NOI18N
        jButton18.setBorderPainted(false);
        jButton18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jButton18);
        jButton18.setBounds(100, 160, 80, 60);

        jButton15.setBackground(new java.awt.Color(18, 18, 20));
        jButton15.setForeground(new java.awt.Color(18, 18, 20));
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/calculadora1.png"))); // NOI18N
        jButton15.setBorderPainted(false);
        jButton15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jButton15);
        jButton15.setBounds(10, 60, 80, 60);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setForeground(java.awt.Color.lightGray);
        jLabel26.setText("Calculadora");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(16, 40, 66, 14);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setForeground(java.awt.Color.lightGray);
        jLabel27.setText("Calendario");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(107, 40, 60, 14);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoTelaPrincipal.png"))); // NOI18N
        jLabel25.setText("jLabel25");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(0, 0, 190, 250);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(820, 290, 190, 250);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setEnabled(false);
        jPanel3.setLayout(null);

        log.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logooo.png"))); // NOI18N
        jPanel3.add(log);
        log.setBounds(530, 20, 155, 149);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(java.awt.Color.lightGray);
        jLabel7.setText("Funcionário");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(100, 0, 70, 30);

        jLabel28.setForeground(java.awt.Color.lightGray);
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bemvindo (2).png"))); // NOI18N
        jLabel28.setText("Bem-Vindo!");
        jPanel3.add(jLabel28);
        jLabel28.setBounds(250, 60, 270, 70);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel29.setForeground(java.awt.Color.lightGray);
        jLabel29.setText("Cargo");
        jPanel3.add(jLabel29);
        jLabel29.setBounds(110, 60, 40, 30);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel30.setForeground(java.awt.Color.lightGray);
        jLabel30.setText("Data");
        jPanel3.add(jLabel30);
        jLabel30.setBounds(60, 120, 40, 30);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel31.setForeground(java.awt.Color.lightGray);
        jLabel31.setText("Hora");
        jPanel3.add(jLabel31);
        jLabel31.setBounds(180, 120, 40, 30);

        txtFuncionario.setBackground(new java.awt.Color(18, 18, 20));
        txtFuncionario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtFuncionario.setForeground(new java.awt.Color(204, 204, 204));
        txtFuncionario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFuncionario.setBorder(null);
        txtFuncionario.setEnabled(false);
        jPanel3.add(txtFuncionario);
        txtFuncionario.setBounds(40, 30, 190, 30);

        txtCargo.setBackground(new java.awt.Color(18, 18, 20));
        txtCargo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtCargo.setForeground(new java.awt.Color(204, 204, 204));
        txtCargo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCargo.setBorder(null);
        txtCargo.setEnabled(false);
        jPanel3.add(txtCargo);
        txtCargo.setBounds(40, 90, 190, 30);

        txtData.setEditable(false);
        txtData.setBackground(new java.awt.Color(18, 18, 20));
        txtData.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtData.setForeground(new java.awt.Color(204, 204, 204));
        txtData.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtData.setBorder(null);
        txtData.setEnabled(false);
        txtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataActionPerformed(evt);
            }
        });
        jPanel3.add(txtData);
        txtData.setBounds(40, 150, 80, 30);

        txtHora.setEditable(false);
        txtHora.setBackground(new java.awt.Color(18, 18, 20));
        txtHora.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtHora.setForeground(new java.awt.Color(204, 204, 204));
        txtHora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHora.setBorder(null);
        txtHora.setEnabled(false);
        jPanel3.add(txtHora);
        txtHora.setBounds(160, 150, 70, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/calen.png"))); // NOI18N
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 150, 24, 30);

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/clock.png"))); // NOI18N
        jPanel3.add(jLabel35);
        jLabel35.setBounds(130, 150, 30, 30);

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/func.png"))); // NOI18N
        jLabel36.setText("jLabel36");
        jPanel3.add(jLabel36);
        jLabel36.setBounds(10, 30, 30, 30);

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cargo.png"))); // NOI18N
        jPanel3.add(jLabel37);
        jLabel37.setBounds(10, 90, 24, 30);

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundocliente1.png"))); // NOI18N
        jLabel41.setText("jLabel30");
        jPanel3.add(jLabel41);
        jLabel41.setBounds(0, 0, 710, 190);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(160, 20, 710, 190);

        jLabel34.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(94, 94, 94));
        jLabel34.setText("TradeTech");
        getContentPane().add(jLabel34);
        jLabel34.setBounds(50, 120, 70, 14);

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/planodefundoapp.png"))); // NOI18N
        fundo.setText("jLabel7");
        getContentPane().add(fundo);
        fundo.setBounds(0, 0, 1030, 570);

        jMenu1.setText("Cadastros");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Cadastros");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Funcionários");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setText("Produtos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem4.setText("Entrega");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Relatórios");

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem10.setText("Cliente");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem11.setText("Funcionário");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_7, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem12.setText("Estoque");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem12);

        jMenuItem13.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_8, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem13.setText("Entrega");
        jMenu2.add(jMenuItem13);

        jMenuItem28.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItem28.setText("Vendas");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem28);

        jMenuItem29.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_8, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItem29.setText("Entregas");
        jMenuItem29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem29ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem29);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Pedidos");

        jMenuItem14.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItem14.setText("Novo Pedido");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem14);

        jMenuItem15.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItem15.setText("Alterar Pedido");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem15);

        jMenuItem16.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItem16.setText("Cancelar Pedido");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem16);

        jMenuItem17.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItem17.setText("Vendas");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem17);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Entrega");

        jMenuItem18.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItem18.setText("Envio");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem18);

        jMenuItem19.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItem19.setText("Alteração");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem19);

        jMenuItem20.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_7, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItem20.setText("Cancelamento");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem20);

        jMenuItem21.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_8, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItem21.setText("Relatório");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem21);

        jMenuBar1.add(jMenu6);

        jMenu10.setText("Acessorios");

        jMenuItem22.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem22.setText("Calculadora");
        jMenu10.add(jMenuItem22);

        jMenuItem23.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem23.setText("Calendário");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem23);

        jMenuItem24.setText("jMenuItem24");
        jMenu10.add(jMenuItem24);

        jMenuItem25.setText("jMenuItem25");
        jMenu10.add(jMenuItem25);

        jMenuBar1.add(jMenu10);

        jMenu15.setText("Ajuda");

        jMenuItem27.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem27.setText("Ajuda");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem27);

        jMenuBar1.add(jMenu15);

        jMenu11.setText("Sair");

        jMenuItem26.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem26.setText("Sair");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem26);

        jMenuBar1.add(jMenu11);

        setJMenuBar(jMenuBar1);

        getAccessibleContext().setAccessibleDescription("");

        setSize(new java.awt.Dimension(1048, 628));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadclienteActionPerformed
        TelaCadCliente tela = new TelaCadCliente(); // Chama Frame de Cadastro de Cliente
        tela.setVisible(true); // torna visibilidade da classe visivel
    }//GEN-LAST:event_jButtonCadclienteActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       TelaCadProd tela = new TelaCadProd();
       tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButtonCadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadFuncActionPerformed
       TelaCadFunc tela = new TelaCadFunc();
       tela.setVisible(true);
    }//GEN-LAST:event_jButtonCadFuncActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
      TelaCadCliente tela = new TelaCadCliente();
      tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
      TelaCadFunc tela = new TelaCadFunc();
      tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButtonCadProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadProdActionPerformed
        TelaCadProd tela = new TelaCadProd();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonCadProdActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        TelaNewPed tela = new TelaNewPed();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        TelaRelCliente tela = new TelaRelCliente();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        TelaEstq tela = new TelaEstq();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jButtonRelClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelClienteActionPerformed
        TelaRelCliente tela = new TelaRelCliente();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonRelClienteActionPerformed

    private void jButtonRelFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelFuncActionPerformed
        TelaRelFunc tela = new TelaRelFunc();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonRelFuncActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
       TelaRelFunc tela = new TelaRelFunc();
       tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jButtonNewPedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewPedActionPerformed
        TelaNewPed tela = new TelaNewPed();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonNewPedActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
       dispose();
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jButtonCadEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadEntActionPerformed
        TelaCadEntrega tela = new TelaCadEntrega();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonCadEntActionPerformed

    private void txtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        Date dataSistema = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        txtData.setText(formato.format(dataSistema));
        
        Timer timer = new Timer(1000, new hora());
        timer.start();
    }//GEN-LAST:event_formWindowOpened

    private void jButtonRelEstoqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelEstoqActionPerformed
       TelaEstq tela = new TelaEstq();
       tela.setVisible(true);
    }//GEN-LAST:event_jButtonRelEstoqActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        TelaAltPed tela = new TelaAltPed();
        tela.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        TelaCadEntrega tela = new TelaCadEntrega();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
       TelaAltPed tela = new TelaAltPed();
       tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
      TelaDelPed tela = new TelaDelPed();
      tela.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jMenuItem29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem29ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        TelaRelEntrega tela = new TelaRelEntrega();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        TelaRelEntrega tela = new TelaRelEntrega();
        tela.setVisible(true);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
      TelaEnvEntrega tela = new TelaEnvEntrega();
      tela.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
       TelaDelEntrega tela = new TelaDelEntrega();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
//        TelaAltEntrega tela = new TelaAltEntrega();
//        tela.setVisible(true);
        JOptionPane.showMessageDialog(null,"Erro: Ainda não impletementadado");
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
         TelaAltEntrega tela = new TelaAltEntrega();
         tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
         TelaDelEntrega tela = new TelaDelEntrega();
         tela.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        TelaRelPedido tela = new TelaRelPedido();
        tela.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButtonRelEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelEntActionPerformed
        TelaRelEntrega tela = new TelaRelEntrega();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonRelEntActionPerformed

    private class hora implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e){
            Calendar now = Calendar.getInstance();
            txtHora.setText(String.format("%1$tH:%1$tM:%1$tS", now));
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fundo;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonCadEnt;
    private javax.swing.JButton jButtonCadFunc;
    private javax.swing.JButton jButtonCadProd;
    private javax.swing.JButton jButtonCadcliente;
    private javax.swing.JButton jButtonNewPed;
    private javax.swing.JButton jButtonRelCliente;
    private javax.swing.JButton jButtonRelEnt;
    private javax.swing.JButton jButtonRelEstoq;
    private javax.swing.JButton jButtonRelFunc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelBotoes;
    private javax.swing.JPanel jPanelEntrega;
    private javax.swing.JPanel jPanelPedidos;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel log;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtFuncionario;
    private javax.swing.JTextField txtHora;
    // End of variables declaration//GEN-END:variables
}
